// Code generated by ent, DO NOT EDIT.

package aicapturesessionitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldSessionID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldClientID, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldEntityID, v))
}

// UploadedPhotoIds applies equality check predicate on the "uploaded_photo_ids" field. It's identical to UploadedPhotoIdsEQ.
func UploadedPhotoIds(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldUploadedPhotoIds, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldErrorCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotIn(FieldSessionID, vs...))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldContainsFold(FieldClientID, v))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v uuid.UUID) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLTE(FieldEntityID, v))
}

// EntityIDIsNil applies the IsNil predicate on the "entity_id" field.
func EntityIDIsNil() predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIsNull(FieldEntityID))
}

// EntityIDNotNil applies the NotNil predicate on the "entity_id" field.
func EntityIDNotNil() predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotNull(FieldEntityID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotIn(FieldStatus, vs...))
}

// UploadedPhotoIdsEQ applies the EQ predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsEQ(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldUploadedPhotoIds, v))
}

// UploadedPhotoIdsNEQ applies the NEQ predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsNEQ(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNEQ(FieldUploadedPhotoIds, v))
}

// UploadedPhotoIdsIn applies the In predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsIn(vs ...string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIn(FieldUploadedPhotoIds, vs...))
}

// UploadedPhotoIdsNotIn applies the NotIn predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsNotIn(vs ...string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotIn(FieldUploadedPhotoIds, vs...))
}

// UploadedPhotoIdsGT applies the GT predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsGT(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGT(FieldUploadedPhotoIds, v))
}

// UploadedPhotoIdsGTE applies the GTE predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsGTE(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGTE(FieldUploadedPhotoIds, v))
}

// UploadedPhotoIdsLT applies the LT predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsLT(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLT(FieldUploadedPhotoIds, v))
}

// UploadedPhotoIdsLTE applies the LTE predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsLTE(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLTE(FieldUploadedPhotoIds, v))
}

// UploadedPhotoIdsContains applies the Contains predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsContains(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldContains(FieldUploadedPhotoIds, v))
}

// UploadedPhotoIdsHasPrefix applies the HasPrefix predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsHasPrefix(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldHasPrefix(FieldUploadedPhotoIds, v))
}

// UploadedPhotoIdsHasSuffix applies the HasSuffix predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsHasSuffix(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldHasSuffix(FieldUploadedPhotoIds, v))
}

// UploadedPhotoIdsEqualFold applies the EqualFold predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsEqualFold(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEqualFold(FieldUploadedPhotoIds, v))
}

// UploadedPhotoIdsContainsFold applies the ContainsFold predicate on the "uploaded_photo_ids" field.
func UploadedPhotoIdsContainsFold(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldContainsFold(FieldUploadedPhotoIds, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.FieldContainsFold(FieldErrorCode, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.AICaptureSession) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AICaptureSessionItem) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AICaptureSessionItem) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AICaptureSessionItem) predicate.AICaptureSessionItem {
	return predicate.AICaptureSessionItem(sql.NotPredicates(p))
}
