// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturephoto"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesessionitem"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// AICaptureSessionUpdate is the builder for updating AICaptureSession entities.
type AICaptureSessionUpdate struct {
	config
	hooks    []Hook
	mutation *AICaptureSessionMutation
}

// Where appends a list predicates to the AICaptureSessionUpdate builder.
func (_u *AICaptureSessionUpdate) Where(ps ...predicate.AICaptureSession) *AICaptureSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AICaptureSessionUpdate) SetUpdatedAt(v time.Time) *AICaptureSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AICaptureSessionUpdate) SetGroupID(v uuid.UUID) *AICaptureSessionUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableGroupID(v *uuid.UUID) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AICaptureSessionUpdate) SetUserID(v uuid.UUID) *AICaptureSessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableUserID(v *uuid.UUID) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLocationID sets the "location_id" field.
func (_u *AICaptureSessionUpdate) SetLocationID(v uuid.UUID) *AICaptureSessionUpdate {
	_u.mutation.SetLocationID(v)
	return _u
}

// SetNillableLocationID sets the "location_id" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableLocationID(v *uuid.UUID) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetLocationID(*v)
	}
	return _u
}

// ClearLocationID clears the value of the "location_id" field.
func (_u *AICaptureSessionUpdate) ClearLocationID() *AICaptureSessionUpdate {
	_u.mutation.ClearLocationID()
	return _u
}

// SetLocationNameSnapshot sets the "location_name_snapshot" field.
func (_u *AICaptureSessionUpdate) SetLocationNameSnapshot(v string) *AICaptureSessionUpdate {
	_u.mutation.SetLocationNameSnapshot(v)
	return _u
}

// SetNillableLocationNameSnapshot sets the "location_name_snapshot" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableLocationNameSnapshot(v *string) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetLocationNameSnapshot(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AICaptureSessionUpdate) SetStatus(v aicapturesession.Status) *AICaptureSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableStatus(v *aicapturesession.Status) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDraftJSON sets the "draft_json" field.
func (_u *AICaptureSessionUpdate) SetDraftJSON(v string) *AICaptureSessionUpdate {
	_u.mutation.SetDraftJSON(v)
	return _u
}

// SetNillableDraftJSON sets the "draft_json" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableDraftJSON(v *string) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetDraftJSON(*v)
	}
	return _u
}

// ClearDraftJSON clears the value of the "draft_json" field.
func (_u *AICaptureSessionUpdate) ClearDraftJSON() *AICaptureSessionUpdate {
	_u.mutation.ClearDraftJSON()
	return _u
}

// SetDraftRevision sets the "draft_revision" field.
func (_u *AICaptureSessionUpdate) SetDraftRevision(v int) *AICaptureSessionUpdate {
	_u.mutation.ResetDraftRevision()
	_u.mutation.SetDraftRevision(v)
	return _u
}

// SetNillableDraftRevision sets the "draft_revision" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableDraftRevision(v *int) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetDraftRevision(*v)
	}
	return _u
}

// AddDraftRevision adds value to the "draft_revision" field.
func (_u *AICaptureSessionUpdate) AddDraftRevision(v int) *AICaptureSessionUpdate {
	_u.mutation.AddDraftRevision(v)
	return _u
}

// SetAnalysisAttempts sets the "analysis_attempts" field.
func (_u *AICaptureSessionUpdate) SetAnalysisAttempts(v int) *AICaptureSessionUpdate {
	_u.mutation.ResetAnalysisAttempts()
	_u.mutation.SetAnalysisAttempts(v)
	return _u
}

// SetNillableAnalysisAttempts sets the "analysis_attempts" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableAnalysisAttempts(v *int) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetAnalysisAttempts(*v)
	}
	return _u
}

// AddAnalysisAttempts adds value to the "analysis_attempts" field.
func (_u *AICaptureSessionUpdate) AddAnalysisAttempts(v int) *AICaptureSessionUpdate {
	_u.mutation.AddAnalysisAttempts(v)
	return _u
}

// SetPhotoCount sets the "photo_count" field.
func (_u *AICaptureSessionUpdate) SetPhotoCount(v int) *AICaptureSessionUpdate {
	_u.mutation.ResetPhotoCount()
	_u.mutation.SetPhotoCount(v)
	return _u
}

// SetNillablePhotoCount sets the "photo_count" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillablePhotoCount(v *int) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetPhotoCount(*v)
	}
	return _u
}

// AddPhotoCount adds value to the "photo_count" field.
func (_u *AICaptureSessionUpdate) AddPhotoCount(v int) *AICaptureSessionUpdate {
	_u.mutation.AddPhotoCount(v)
	return _u
}

// SetWorkerLeaseUntil sets the "worker_lease_until" field.
func (_u *AICaptureSessionUpdate) SetWorkerLeaseUntil(v time.Time) *AICaptureSessionUpdate {
	_u.mutation.SetWorkerLeaseUntil(v)
	return _u
}

// SetNillableWorkerLeaseUntil sets the "worker_lease_until" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableWorkerLeaseUntil(v *time.Time) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetWorkerLeaseUntil(*v)
	}
	return _u
}

// ClearWorkerLeaseUntil clears the value of the "worker_lease_until" field.
func (_u *AICaptureSessionUpdate) ClearWorkerLeaseUntil() *AICaptureSessionUpdate {
	_u.mutation.ClearWorkerLeaseUntil()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *AICaptureSessionUpdate) SetErrorCode(v string) *AICaptureSessionUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableErrorCode(v *string) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *AICaptureSessionUpdate) ClearErrorCode() *AICaptureSessionUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AICaptureSessionUpdate) SetErrorMessage(v string) *AICaptureSessionUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableErrorMessage(v *string) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AICaptureSessionUpdate) ClearErrorMessage() *AICaptureSessionUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *AICaptureSessionUpdate) SetFinishedAt(v time.Time) *AICaptureSessionUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableFinishedAt(v *time.Time) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *AICaptureSessionUpdate) ClearFinishedAt() *AICaptureSessionUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetAnalyzedAt sets the "analyzed_at" field.
func (_u *AICaptureSessionUpdate) SetAnalyzedAt(v time.Time) *AICaptureSessionUpdate {
	_u.mutation.SetAnalyzedAt(v)
	return _u
}

// SetNillableAnalyzedAt sets the "analyzed_at" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableAnalyzedAt(v *time.Time) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetAnalyzedAt(*v)
	}
	return _u
}

// ClearAnalyzedAt clears the value of the "analyzed_at" field.
func (_u *AICaptureSessionUpdate) ClearAnalyzedAt() *AICaptureSessionUpdate {
	_u.mutation.ClearAnalyzedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *AICaptureSessionUpdate) SetCompletedAt(v time.Time) *AICaptureSessionUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableCompletedAt(v *time.Time) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *AICaptureSessionUpdate) ClearCompletedAt() *AICaptureSessionUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AICaptureSessionUpdate) SetExpiresAt(v time.Time) *AICaptureSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AICaptureSessionUpdate) SetNillableExpiresAt(v *time.Time) *AICaptureSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *AICaptureSessionUpdate) SetGroup(v *Group) *AICaptureSessionUpdate {
	return _u.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AICaptureSessionUpdate) SetUser(v *User) *AICaptureSessionUpdate {
	return _u.SetUserID(v.ID)
}

// SetLocation sets the "location" edge to the Entity entity.
func (_u *AICaptureSessionUpdate) SetLocation(v *Entity) *AICaptureSessionUpdate {
	return _u.SetLocationID(v.ID)
}

// AddPhotoIDs adds the "photos" edge to the AICapturePhoto entity by IDs.
func (_u *AICaptureSessionUpdate) AddPhotoIDs(ids ...uuid.UUID) *AICaptureSessionUpdate {
	_u.mutation.AddPhotoIDs(ids...)
	return _u
}

// AddPhotos adds the "photos" edges to the AICapturePhoto entity.
func (_u *AICaptureSessionUpdate) AddPhotos(v ...*AICapturePhoto) *AICaptureSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPhotoIDs(ids...)
}

// AddItemIDs adds the "items" edge to the AICaptureSessionItem entity by IDs.
func (_u *AICaptureSessionUpdate) AddItemIDs(ids ...uuid.UUID) *AICaptureSessionUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the AICaptureSessionItem entity.
func (_u *AICaptureSessionUpdate) AddItems(v ...*AICaptureSessionItem) *AICaptureSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the AICaptureSessionMutation object of the builder.
func (_u *AICaptureSessionUpdate) Mutation() *AICaptureSessionMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *AICaptureSessionUpdate) ClearGroup() *AICaptureSessionUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AICaptureSessionUpdate) ClearUser() *AICaptureSessionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearLocation clears the "location" edge to the Entity entity.
func (_u *AICaptureSessionUpdate) ClearLocation() *AICaptureSessionUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// ClearPhotos clears all "photos" edges to the AICapturePhoto entity.
func (_u *AICaptureSessionUpdate) ClearPhotos() *AICaptureSessionUpdate {
	_u.mutation.ClearPhotos()
	return _u
}

// RemovePhotoIDs removes the "photos" edge to AICapturePhoto entities by IDs.
func (_u *AICaptureSessionUpdate) RemovePhotoIDs(ids ...uuid.UUID) *AICaptureSessionUpdate {
	_u.mutation.RemovePhotoIDs(ids...)
	return _u
}

// RemovePhotos removes "photos" edges to AICapturePhoto entities.
func (_u *AICaptureSessionUpdate) RemovePhotos(v ...*AICapturePhoto) *AICaptureSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePhotoIDs(ids...)
}

// ClearItems clears all "items" edges to the AICaptureSessionItem entity.
func (_u *AICaptureSessionUpdate) ClearItems() *AICaptureSessionUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to AICaptureSessionItem entities by IDs.
func (_u *AICaptureSessionUpdate) RemoveItemIDs(ids ...uuid.UUID) *AICaptureSessionUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to AICaptureSessionItem entities.
func (_u *AICaptureSessionUpdate) RemoveItems(v ...*AICaptureSessionItem) *AICaptureSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AICaptureSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AICaptureSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AICaptureSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AICaptureSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AICaptureSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aicapturesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AICaptureSessionUpdate) check() error {
	if v, ok := _u.mutation.LocationNameSnapshot(); ok {
		if err := aicapturesession.LocationNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "location_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.location_name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := aicapturesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := aicapturesession.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := aicapturesession.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.error_message": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AICaptureSession.group"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AICaptureSession.user"`)
	}
	return nil
}

func (_u *AICaptureSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aicapturesession.Table, aicapturesession.Columns, sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aicapturesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LocationNameSnapshot(); ok {
		_spec.SetField(aicapturesession.FieldLocationNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aicapturesession.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DraftJSON(); ok {
		_spec.SetField(aicapturesession.FieldDraftJSON, field.TypeString, value)
	}
	if _u.mutation.DraftJSONCleared() {
		_spec.ClearField(aicapturesession.FieldDraftJSON, field.TypeString)
	}
	if value, ok := _u.mutation.DraftRevision(); ok {
		_spec.SetField(aicapturesession.FieldDraftRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDraftRevision(); ok {
		_spec.AddField(aicapturesession.FieldDraftRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AnalysisAttempts(); ok {
		_spec.SetField(aicapturesession.FieldAnalysisAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAnalysisAttempts(); ok {
		_spec.AddField(aicapturesession.FieldAnalysisAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PhotoCount(); ok {
		_spec.SetField(aicapturesession.FieldPhotoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPhotoCount(); ok {
		_spec.AddField(aicapturesession.FieldPhotoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WorkerLeaseUntil(); ok {
		_spec.SetField(aicapturesession.FieldWorkerLeaseUntil, field.TypeTime, value)
	}
	if _u.mutation.WorkerLeaseUntilCleared() {
		_spec.ClearField(aicapturesession.FieldWorkerLeaseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(aicapturesession.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(aicapturesession.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(aicapturesession.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(aicapturesession.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(aicapturesession.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(aicapturesession.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AnalyzedAt(); ok {
		_spec.SetField(aicapturesession.FieldAnalyzedAt, field.TypeTime, value)
	}
	if _u.mutation.AnalyzedAtCleared() {
		_spec.ClearField(aicapturesession.FieldAnalyzedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(aicapturesession.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(aicapturesession.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(aicapturesession.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.GroupTable,
			Columns: []string{aicapturesession.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.GroupTable,
			Columns: []string{aicapturesession.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.UserTable,
			Columns: []string{aicapturesession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.UserTable,
			Columns: []string{aicapturesession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.LocationTable,
			Columns: []string{aicapturesession.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.LocationTable,
			Columns: []string{aicapturesession.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PhotosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.PhotosTable,
			Columns: []string{aicapturesession.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPhotosIDs(); len(nodes) > 0 && !_u.mutation.PhotosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.PhotosTable,
			Columns: []string{aicapturesession.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PhotosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.PhotosTable,
			Columns: []string{aicapturesession.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.ItemsTable,
			Columns: []string{aicapturesession.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesessionitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.ItemsTable,
			Columns: []string{aicapturesession.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesessionitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.ItemsTable,
			Columns: []string{aicapturesession.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesessionitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aicapturesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AICaptureSessionUpdateOne is the builder for updating a single AICaptureSession entity.
type AICaptureSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AICaptureSessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AICaptureSessionUpdateOne) SetUpdatedAt(v time.Time) *AICaptureSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AICaptureSessionUpdateOne) SetGroupID(v uuid.UUID) *AICaptureSessionUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableGroupID(v *uuid.UUID) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AICaptureSessionUpdateOne) SetUserID(v uuid.UUID) *AICaptureSessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableUserID(v *uuid.UUID) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLocationID sets the "location_id" field.
func (_u *AICaptureSessionUpdateOne) SetLocationID(v uuid.UUID) *AICaptureSessionUpdateOne {
	_u.mutation.SetLocationID(v)
	return _u
}

// SetNillableLocationID sets the "location_id" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableLocationID(v *uuid.UUID) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetLocationID(*v)
	}
	return _u
}

// ClearLocationID clears the value of the "location_id" field.
func (_u *AICaptureSessionUpdateOne) ClearLocationID() *AICaptureSessionUpdateOne {
	_u.mutation.ClearLocationID()
	return _u
}

// SetLocationNameSnapshot sets the "location_name_snapshot" field.
func (_u *AICaptureSessionUpdateOne) SetLocationNameSnapshot(v string) *AICaptureSessionUpdateOne {
	_u.mutation.SetLocationNameSnapshot(v)
	return _u
}

// SetNillableLocationNameSnapshot sets the "location_name_snapshot" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableLocationNameSnapshot(v *string) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetLocationNameSnapshot(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AICaptureSessionUpdateOne) SetStatus(v aicapturesession.Status) *AICaptureSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableStatus(v *aicapturesession.Status) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDraftJSON sets the "draft_json" field.
func (_u *AICaptureSessionUpdateOne) SetDraftJSON(v string) *AICaptureSessionUpdateOne {
	_u.mutation.SetDraftJSON(v)
	return _u
}

// SetNillableDraftJSON sets the "draft_json" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableDraftJSON(v *string) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetDraftJSON(*v)
	}
	return _u
}

// ClearDraftJSON clears the value of the "draft_json" field.
func (_u *AICaptureSessionUpdateOne) ClearDraftJSON() *AICaptureSessionUpdateOne {
	_u.mutation.ClearDraftJSON()
	return _u
}

// SetDraftRevision sets the "draft_revision" field.
func (_u *AICaptureSessionUpdateOne) SetDraftRevision(v int) *AICaptureSessionUpdateOne {
	_u.mutation.ResetDraftRevision()
	_u.mutation.SetDraftRevision(v)
	return _u
}

// SetNillableDraftRevision sets the "draft_revision" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableDraftRevision(v *int) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetDraftRevision(*v)
	}
	return _u
}

// AddDraftRevision adds value to the "draft_revision" field.
func (_u *AICaptureSessionUpdateOne) AddDraftRevision(v int) *AICaptureSessionUpdateOne {
	_u.mutation.AddDraftRevision(v)
	return _u
}

// SetAnalysisAttempts sets the "analysis_attempts" field.
func (_u *AICaptureSessionUpdateOne) SetAnalysisAttempts(v int) *AICaptureSessionUpdateOne {
	_u.mutation.ResetAnalysisAttempts()
	_u.mutation.SetAnalysisAttempts(v)
	return _u
}

// SetNillableAnalysisAttempts sets the "analysis_attempts" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableAnalysisAttempts(v *int) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetAnalysisAttempts(*v)
	}
	return _u
}

// AddAnalysisAttempts adds value to the "analysis_attempts" field.
func (_u *AICaptureSessionUpdateOne) AddAnalysisAttempts(v int) *AICaptureSessionUpdateOne {
	_u.mutation.AddAnalysisAttempts(v)
	return _u
}

// SetPhotoCount sets the "photo_count" field.
func (_u *AICaptureSessionUpdateOne) SetPhotoCount(v int) *AICaptureSessionUpdateOne {
	_u.mutation.ResetPhotoCount()
	_u.mutation.SetPhotoCount(v)
	return _u
}

// SetNillablePhotoCount sets the "photo_count" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillablePhotoCount(v *int) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetPhotoCount(*v)
	}
	return _u
}

// AddPhotoCount adds value to the "photo_count" field.
func (_u *AICaptureSessionUpdateOne) AddPhotoCount(v int) *AICaptureSessionUpdateOne {
	_u.mutation.AddPhotoCount(v)
	return _u
}

// SetWorkerLeaseUntil sets the "worker_lease_until" field.
func (_u *AICaptureSessionUpdateOne) SetWorkerLeaseUntil(v time.Time) *AICaptureSessionUpdateOne {
	_u.mutation.SetWorkerLeaseUntil(v)
	return _u
}

// SetNillableWorkerLeaseUntil sets the "worker_lease_until" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableWorkerLeaseUntil(v *time.Time) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetWorkerLeaseUntil(*v)
	}
	return _u
}

// ClearWorkerLeaseUntil clears the value of the "worker_lease_until" field.
func (_u *AICaptureSessionUpdateOne) ClearWorkerLeaseUntil() *AICaptureSessionUpdateOne {
	_u.mutation.ClearWorkerLeaseUntil()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *AICaptureSessionUpdateOne) SetErrorCode(v string) *AICaptureSessionUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableErrorCode(v *string) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *AICaptureSessionUpdateOne) ClearErrorCode() *AICaptureSessionUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AICaptureSessionUpdateOne) SetErrorMessage(v string) *AICaptureSessionUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableErrorMessage(v *string) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AICaptureSessionUpdateOne) ClearErrorMessage() *AICaptureSessionUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *AICaptureSessionUpdateOne) SetFinishedAt(v time.Time) *AICaptureSessionUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableFinishedAt(v *time.Time) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *AICaptureSessionUpdateOne) ClearFinishedAt() *AICaptureSessionUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetAnalyzedAt sets the "analyzed_at" field.
func (_u *AICaptureSessionUpdateOne) SetAnalyzedAt(v time.Time) *AICaptureSessionUpdateOne {
	_u.mutation.SetAnalyzedAt(v)
	return _u
}

// SetNillableAnalyzedAt sets the "analyzed_at" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableAnalyzedAt(v *time.Time) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetAnalyzedAt(*v)
	}
	return _u
}

// ClearAnalyzedAt clears the value of the "analyzed_at" field.
func (_u *AICaptureSessionUpdateOne) ClearAnalyzedAt() *AICaptureSessionUpdateOne {
	_u.mutation.ClearAnalyzedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *AICaptureSessionUpdateOne) SetCompletedAt(v time.Time) *AICaptureSessionUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableCompletedAt(v *time.Time) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *AICaptureSessionUpdateOne) ClearCompletedAt() *AICaptureSessionUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AICaptureSessionUpdateOne) SetExpiresAt(v time.Time) *AICaptureSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AICaptureSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *AICaptureSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *AICaptureSessionUpdateOne) SetGroup(v *Group) *AICaptureSessionUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AICaptureSessionUpdateOne) SetUser(v *User) *AICaptureSessionUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetLocation sets the "location" edge to the Entity entity.
func (_u *AICaptureSessionUpdateOne) SetLocation(v *Entity) *AICaptureSessionUpdateOne {
	return _u.SetLocationID(v.ID)
}

// AddPhotoIDs adds the "photos" edge to the AICapturePhoto entity by IDs.
func (_u *AICaptureSessionUpdateOne) AddPhotoIDs(ids ...uuid.UUID) *AICaptureSessionUpdateOne {
	_u.mutation.AddPhotoIDs(ids...)
	return _u
}

// AddPhotos adds the "photos" edges to the AICapturePhoto entity.
func (_u *AICaptureSessionUpdateOne) AddPhotos(v ...*AICapturePhoto) *AICaptureSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPhotoIDs(ids...)
}

// AddItemIDs adds the "items" edge to the AICaptureSessionItem entity by IDs.
func (_u *AICaptureSessionUpdateOne) AddItemIDs(ids ...uuid.UUID) *AICaptureSessionUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the AICaptureSessionItem entity.
func (_u *AICaptureSessionUpdateOne) AddItems(v ...*AICaptureSessionItem) *AICaptureSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the AICaptureSessionMutation object of the builder.
func (_u *AICaptureSessionUpdateOne) Mutation() *AICaptureSessionMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *AICaptureSessionUpdateOne) ClearGroup() *AICaptureSessionUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AICaptureSessionUpdateOne) ClearUser() *AICaptureSessionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearLocation clears the "location" edge to the Entity entity.
func (_u *AICaptureSessionUpdateOne) ClearLocation() *AICaptureSessionUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// ClearPhotos clears all "photos" edges to the AICapturePhoto entity.
func (_u *AICaptureSessionUpdateOne) ClearPhotos() *AICaptureSessionUpdateOne {
	_u.mutation.ClearPhotos()
	return _u
}

// RemovePhotoIDs removes the "photos" edge to AICapturePhoto entities by IDs.
func (_u *AICaptureSessionUpdateOne) RemovePhotoIDs(ids ...uuid.UUID) *AICaptureSessionUpdateOne {
	_u.mutation.RemovePhotoIDs(ids...)
	return _u
}

// RemovePhotos removes "photos" edges to AICapturePhoto entities.
func (_u *AICaptureSessionUpdateOne) RemovePhotos(v ...*AICapturePhoto) *AICaptureSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePhotoIDs(ids...)
}

// ClearItems clears all "items" edges to the AICaptureSessionItem entity.
func (_u *AICaptureSessionUpdateOne) ClearItems() *AICaptureSessionUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to AICaptureSessionItem entities by IDs.
func (_u *AICaptureSessionUpdateOne) RemoveItemIDs(ids ...uuid.UUID) *AICaptureSessionUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to AICaptureSessionItem entities.
func (_u *AICaptureSessionUpdateOne) RemoveItems(v ...*AICaptureSessionItem) *AICaptureSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the AICaptureSessionUpdate builder.
func (_u *AICaptureSessionUpdateOne) Where(ps ...predicate.AICaptureSession) *AICaptureSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AICaptureSessionUpdateOne) Select(field string, fields ...string) *AICaptureSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AICaptureSession entity.
func (_u *AICaptureSessionUpdateOne) Save(ctx context.Context) (*AICaptureSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AICaptureSessionUpdateOne) SaveX(ctx context.Context) *AICaptureSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AICaptureSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AICaptureSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AICaptureSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aicapturesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AICaptureSessionUpdateOne) check() error {
	if v, ok := _u.mutation.LocationNameSnapshot(); ok {
		if err := aicapturesession.LocationNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "location_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.location_name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := aicapturesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := aicapturesession.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorMessage(); ok {
		if err := aicapturesession.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.error_message": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AICaptureSession.group"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AICaptureSession.user"`)
	}
	return nil
}

func (_u *AICaptureSessionUpdateOne) sqlSave(ctx context.Context) (_node *AICaptureSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aicapturesession.Table, aicapturesession.Columns, sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AICaptureSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aicapturesession.FieldID)
		for _, f := range fields {
			if !aicapturesession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aicapturesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aicapturesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LocationNameSnapshot(); ok {
		_spec.SetField(aicapturesession.FieldLocationNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aicapturesession.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DraftJSON(); ok {
		_spec.SetField(aicapturesession.FieldDraftJSON, field.TypeString, value)
	}
	if _u.mutation.DraftJSONCleared() {
		_spec.ClearField(aicapturesession.FieldDraftJSON, field.TypeString)
	}
	if value, ok := _u.mutation.DraftRevision(); ok {
		_spec.SetField(aicapturesession.FieldDraftRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDraftRevision(); ok {
		_spec.AddField(aicapturesession.FieldDraftRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AnalysisAttempts(); ok {
		_spec.SetField(aicapturesession.FieldAnalysisAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAnalysisAttempts(); ok {
		_spec.AddField(aicapturesession.FieldAnalysisAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PhotoCount(); ok {
		_spec.SetField(aicapturesession.FieldPhotoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPhotoCount(); ok {
		_spec.AddField(aicapturesession.FieldPhotoCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WorkerLeaseUntil(); ok {
		_spec.SetField(aicapturesession.FieldWorkerLeaseUntil, field.TypeTime, value)
	}
	if _u.mutation.WorkerLeaseUntilCleared() {
		_spec.ClearField(aicapturesession.FieldWorkerLeaseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(aicapturesession.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(aicapturesession.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(aicapturesession.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(aicapturesession.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(aicapturesession.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(aicapturesession.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AnalyzedAt(); ok {
		_spec.SetField(aicapturesession.FieldAnalyzedAt, field.TypeTime, value)
	}
	if _u.mutation.AnalyzedAtCleared() {
		_spec.ClearField(aicapturesession.FieldAnalyzedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(aicapturesession.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(aicapturesession.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(aicapturesession.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.GroupTable,
			Columns: []string{aicapturesession.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.GroupTable,
			Columns: []string{aicapturesession.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.UserTable,
			Columns: []string{aicapturesession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.UserTable,
			Columns: []string{aicapturesession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.LocationTable,
			Columns: []string{aicapturesession.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.LocationTable,
			Columns: []string{aicapturesession.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PhotosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.PhotosTable,
			Columns: []string{aicapturesession.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPhotosIDs(); len(nodes) > 0 && !_u.mutation.PhotosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.PhotosTable,
			Columns: []string{aicapturesession.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PhotosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.PhotosTable,
			Columns: []string{aicapturesession.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.ItemsTable,
			Columns: []string{aicapturesession.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesessionitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.ItemsTable,
			Columns: []string{aicapturesession.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesessionitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.ItemsTable,
			Columns: []string{aicapturesession.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesessionitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AICaptureSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aicapturesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
