// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesessionitem"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// AICaptureSessionItemUpdate is the builder for updating AICaptureSessionItem entities.
type AICaptureSessionItemUpdate struct {
	config
	hooks    []Hook
	mutation *AICaptureSessionItemMutation
}

// Where appends a list predicates to the AICaptureSessionItemUpdate builder.
func (_u *AICaptureSessionItemUpdate) Where(ps ...predicate.AICaptureSessionItem) *AICaptureSessionItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AICaptureSessionItemUpdate) SetUpdatedAt(v time.Time) *AICaptureSessionItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AICaptureSessionItemUpdate) SetSessionID(v uuid.UUID) *AICaptureSessionItemUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdate) SetNillableSessionID(v *uuid.UUID) *AICaptureSessionItemUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AICaptureSessionItemUpdate) SetClientID(v string) *AICaptureSessionItemUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdate) SetNillableClientID(v *string) *AICaptureSessionItemUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *AICaptureSessionItemUpdate) SetEntityID(v uuid.UUID) *AICaptureSessionItemUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdate) SetNillableEntityID(v *uuid.UUID) *AICaptureSessionItemUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *AICaptureSessionItemUpdate) ClearEntityID() *AICaptureSessionItemUpdate {
	_u.mutation.ClearEntityID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AICaptureSessionItemUpdate) SetStatus(v aicapturesessionitem.Status) *AICaptureSessionItemUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdate) SetNillableStatus(v *aicapturesessionitem.Status) *AICaptureSessionItemUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUploadedPhotoIds sets the "uploaded_photo_ids" field.
func (_u *AICaptureSessionItemUpdate) SetUploadedPhotoIds(v string) *AICaptureSessionItemUpdate {
	_u.mutation.SetUploadedPhotoIds(v)
	return _u
}

// SetNillableUploadedPhotoIds sets the "uploaded_photo_ids" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdate) SetNillableUploadedPhotoIds(v *string) *AICaptureSessionItemUpdate {
	if v != nil {
		_u.SetUploadedPhotoIds(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *AICaptureSessionItemUpdate) SetErrorCode(v string) *AICaptureSessionItemUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdate) SetNillableErrorCode(v *string) *AICaptureSessionItemUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *AICaptureSessionItemUpdate) ClearErrorCode() *AICaptureSessionItemUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetSession sets the "session" edge to the AICaptureSession entity.
func (_u *AICaptureSessionItemUpdate) SetSession(v *AICaptureSession) *AICaptureSessionItemUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the AICaptureSessionItemMutation object of the builder.
func (_u *AICaptureSessionItemUpdate) Mutation() *AICaptureSessionItemMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the AICaptureSession entity.
func (_u *AICaptureSessionItemUpdate) ClearSession() *AICaptureSessionItemUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AICaptureSessionItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AICaptureSessionItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AICaptureSessionItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AICaptureSessionItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AICaptureSessionItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aicapturesessionitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AICaptureSessionItemUpdate) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := aicapturesessionitem.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "AICaptureSessionItem.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := aicapturesessionitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AICaptureSessionItem.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := aicapturesessionitem.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "AICaptureSessionItem.error_code": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AICaptureSessionItem.session"`)
	}
	return nil
}

func (_u *AICaptureSessionItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aicapturesessionitem.Table, aicapturesessionitem.Columns, sqlgraph.NewFieldSpec(aicapturesessionitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aicapturesessionitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(aicapturesessionitem.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(aicapturesessionitem.FieldEntityID, field.TypeUUID, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(aicapturesessionitem.FieldEntityID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aicapturesessionitem.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UploadedPhotoIds(); ok {
		_spec.SetField(aicapturesessionitem.FieldUploadedPhotoIds, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(aicapturesessionitem.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(aicapturesessionitem.FieldErrorCode, field.TypeString)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesessionitem.SessionTable,
			Columns: []string{aicapturesessionitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesessionitem.SessionTable,
			Columns: []string{aicapturesessionitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aicapturesessionitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AICaptureSessionItemUpdateOne is the builder for updating a single AICaptureSessionItem entity.
type AICaptureSessionItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AICaptureSessionItemMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AICaptureSessionItemUpdateOne) SetUpdatedAt(v time.Time) *AICaptureSessionItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AICaptureSessionItemUpdateOne) SetSessionID(v uuid.UUID) *AICaptureSessionItemUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdateOne) SetNillableSessionID(v *uuid.UUID) *AICaptureSessionItemUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AICaptureSessionItemUpdateOne) SetClientID(v string) *AICaptureSessionItemUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdateOne) SetNillableClientID(v *string) *AICaptureSessionItemUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *AICaptureSessionItemUpdateOne) SetEntityID(v uuid.UUID) *AICaptureSessionItemUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdateOne) SetNillableEntityID(v *uuid.UUID) *AICaptureSessionItemUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *AICaptureSessionItemUpdateOne) ClearEntityID() *AICaptureSessionItemUpdateOne {
	_u.mutation.ClearEntityID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AICaptureSessionItemUpdateOne) SetStatus(v aicapturesessionitem.Status) *AICaptureSessionItemUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdateOne) SetNillableStatus(v *aicapturesessionitem.Status) *AICaptureSessionItemUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUploadedPhotoIds sets the "uploaded_photo_ids" field.
func (_u *AICaptureSessionItemUpdateOne) SetUploadedPhotoIds(v string) *AICaptureSessionItemUpdateOne {
	_u.mutation.SetUploadedPhotoIds(v)
	return _u
}

// SetNillableUploadedPhotoIds sets the "uploaded_photo_ids" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdateOne) SetNillableUploadedPhotoIds(v *string) *AICaptureSessionItemUpdateOne {
	if v != nil {
		_u.SetUploadedPhotoIds(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *AICaptureSessionItemUpdateOne) SetErrorCode(v string) *AICaptureSessionItemUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *AICaptureSessionItemUpdateOne) SetNillableErrorCode(v *string) *AICaptureSessionItemUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *AICaptureSessionItemUpdateOne) ClearErrorCode() *AICaptureSessionItemUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetSession sets the "session" edge to the AICaptureSession entity.
func (_u *AICaptureSessionItemUpdateOne) SetSession(v *AICaptureSession) *AICaptureSessionItemUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the AICaptureSessionItemMutation object of the builder.
func (_u *AICaptureSessionItemUpdateOne) Mutation() *AICaptureSessionItemMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the AICaptureSession entity.
func (_u *AICaptureSessionItemUpdateOne) ClearSession() *AICaptureSessionItemUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the AICaptureSessionItemUpdate builder.
func (_u *AICaptureSessionItemUpdateOne) Where(ps ...predicate.AICaptureSessionItem) *AICaptureSessionItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AICaptureSessionItemUpdateOne) Select(field string, fields ...string) *AICaptureSessionItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AICaptureSessionItem entity.
func (_u *AICaptureSessionItemUpdateOne) Save(ctx context.Context) (*AICaptureSessionItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AICaptureSessionItemUpdateOne) SaveX(ctx context.Context) *AICaptureSessionItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AICaptureSessionItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AICaptureSessionItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AICaptureSessionItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aicapturesessionitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AICaptureSessionItemUpdateOne) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := aicapturesessionitem.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "AICaptureSessionItem.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := aicapturesessionitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AICaptureSessionItem.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := aicapturesessionitem.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "AICaptureSessionItem.error_code": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AICaptureSessionItem.session"`)
	}
	return nil
}

func (_u *AICaptureSessionItemUpdateOne) sqlSave(ctx context.Context) (_node *AICaptureSessionItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aicapturesessionitem.Table, aicapturesessionitem.Columns, sqlgraph.NewFieldSpec(aicapturesessionitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AICaptureSessionItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aicapturesessionitem.FieldID)
		for _, f := range fields {
			if !aicapturesessionitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aicapturesessionitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aicapturesessionitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(aicapturesessionitem.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(aicapturesessionitem.FieldEntityID, field.TypeUUID, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(aicapturesessionitem.FieldEntityID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(aicapturesessionitem.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UploadedPhotoIds(); ok {
		_spec.SetField(aicapturesessionitem.FieldUploadedPhotoIds, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(aicapturesessionitem.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(aicapturesessionitem.FieldErrorCode, field.TypeString)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesessionitem.SessionTable,
			Columns: []string{aicapturesessionitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesessionitem.SessionTable,
			Columns: []string{aicapturesessionitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AICaptureSessionItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aicapturesessionitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
