// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturephoto"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesession"
)

// AICapturePhotoCreate is the builder for creating a AICapturePhoto entity.
type AICapturePhotoCreate struct {
	config
	mutation *AICapturePhotoMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AICapturePhotoCreate) SetCreatedAt(v time.Time) *AICapturePhotoCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AICapturePhotoCreate) SetNillableCreatedAt(v *time.Time) *AICapturePhotoCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AICapturePhotoCreate) SetUpdatedAt(v time.Time) *AICapturePhotoCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AICapturePhotoCreate) SetNillableUpdatedAt(v *time.Time) *AICapturePhotoCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AICapturePhotoCreate) SetSessionID(v uuid.UUID) *AICapturePhotoCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetClientPhotoID sets the "client_photo_id" field.
func (_c *AICapturePhotoCreate) SetClientPhotoID(v uuid.UUID) *AICapturePhotoCreate {
	_c.mutation.SetClientPhotoID(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *AICapturePhotoCreate) SetPosition(v int) *AICapturePhotoCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetOriginalName sets the "original_name" field.
func (_c *AICapturePhotoCreate) SetOriginalName(v string) *AICapturePhotoCreate {
	_c.mutation.SetOriginalName(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *AICapturePhotoCreate) SetPath(v string) *AICapturePhotoCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *AICapturePhotoCreate) SetMimeType(v string) *AICapturePhotoCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *AICapturePhotoCreate) SetSizeBytes(v int64) *AICapturePhotoCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *AICapturePhotoCreate) SetContentHash(v string) *AICapturePhotoCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AICapturePhotoCreate) SetID(v uuid.UUID) *AICapturePhotoCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AICapturePhotoCreate) SetNillableID(v *uuid.UUID) *AICapturePhotoCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSession sets the "session" edge to the AICaptureSession entity.
func (_c *AICapturePhotoCreate) SetSession(v *AICaptureSession) *AICapturePhotoCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the AICapturePhotoMutation object of the builder.
func (_c *AICapturePhotoCreate) Mutation() *AICapturePhotoMutation {
	return _c.mutation
}

// Save creates the AICapturePhoto in the database.
func (_c *AICapturePhotoCreate) Save(ctx context.Context) (*AICapturePhoto, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AICapturePhotoCreate) SaveX(ctx context.Context) *AICapturePhoto {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AICapturePhotoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AICapturePhotoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AICapturePhotoCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := aicapturephoto.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := aicapturephoto.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := aicapturephoto.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AICapturePhotoCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AICapturePhoto.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AICapturePhoto.updated_at"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "AICapturePhoto.session_id"`)}
	}
	if _, ok := _c.mutation.ClientPhotoID(); !ok {
		return &ValidationError{Name: "client_photo_id", err: errors.New(`ent: missing required field "AICapturePhoto.client_photo_id"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "AICapturePhoto.position"`)}
	}
	if v, ok := _c.mutation.Position(); ok {
		if err := aicapturephoto.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.position": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginalName(); !ok {
		return &ValidationError{Name: "original_name", err: errors.New(`ent: missing required field "AICapturePhoto.original_name"`)}
	}
	if v, ok := _c.mutation.OriginalName(); ok {
		if err := aicapturephoto.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.original_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "AICapturePhoto.path"`)}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "AICapturePhoto.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := aicapturephoto.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "AICapturePhoto.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := aicapturephoto.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.size_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentHash(); !ok {
		return &ValidationError{Name: "content_hash", err: errors.New(`ent: missing required field "AICapturePhoto.content_hash"`)}
	}
	if v, ok := _c.mutation.ContentHash(); ok {
		if err := aicapturephoto.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.content_hash": %w`, err)}
		}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "AICapturePhoto.session"`)}
	}
	return nil
}

func (_c *AICapturePhotoCreate) sqlSave(ctx context.Context) (*AICapturePhoto, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AICapturePhotoCreate) createSpec() (*AICapturePhoto, *sqlgraph.CreateSpec) {
	var (
		_node = &AICapturePhoto{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aicapturephoto.Table, sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(aicapturephoto.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(aicapturephoto.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClientPhotoID(); ok {
		_spec.SetField(aicapturephoto.FieldClientPhotoID, field.TypeUUID, value)
		_node.ClientPhotoID = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(aicapturephoto.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.OriginalName(); ok {
		_spec.SetField(aicapturephoto.FieldOriginalName, field.TypeString, value)
		_node.OriginalName = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(aicapturephoto.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(aicapturephoto.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(aicapturephoto.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(aicapturephoto.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturephoto.SessionTable,
			Columns: []string{aicapturephoto.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AICapturePhotoCreateBulk is the builder for creating many AICapturePhoto entities in bulk.
type AICapturePhotoCreateBulk struct {
	config
	err      error
	builders []*AICapturePhotoCreate
}

// Save creates the AICapturePhoto entities in the database.
func (_c *AICapturePhotoCreateBulk) Save(ctx context.Context) ([]*AICapturePhoto, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AICapturePhoto, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AICapturePhotoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AICapturePhotoCreateBulk) SaveX(ctx context.Context) []*AICapturePhoto {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AICapturePhotoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AICapturePhotoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
