// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesessionitem"
)

// AICaptureSessionItem is the model entity for the AICaptureSessionItem schema.
type AICaptureSessionItem struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID *uuid.UUID `json:"entity_id,omitempty"`
	// Status holds the value of the "status" field.
	Status aicapturesessionitem.Status `json:"status,omitempty"`
	// UploadedPhotoIds holds the value of the "uploaded_photo_ids" field.
	UploadedPhotoIds string `json:"uploaded_photo_ids,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode string `json:"error_code,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AICaptureSessionItemQuery when eager-loading is set.
	Edges        AICaptureSessionItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AICaptureSessionItemEdges holds the relations/edges for other nodes in the graph.
type AICaptureSessionItemEdges struct {
	// Session holds the value of the session edge.
	Session *AICaptureSession `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AICaptureSessionItemEdges) SessionOrErr() (*AICaptureSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aicapturesession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AICaptureSessionItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aicapturesessionitem.FieldEntityID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case aicapturesessionitem.FieldClientID, aicapturesessionitem.FieldStatus, aicapturesessionitem.FieldUploadedPhotoIds, aicapturesessionitem.FieldErrorCode:
			values[i] = new(sql.NullString)
		case aicapturesessionitem.FieldCreatedAt, aicapturesessionitem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case aicapturesessionitem.FieldID, aicapturesessionitem.FieldSessionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AICaptureSessionItem fields.
func (_m *AICaptureSessionItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aicapturesessionitem.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case aicapturesessionitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case aicapturesessionitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case aicapturesessionitem.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				_m.SessionID = *value
			}
		case aicapturesessionitem.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case aicapturesessionitem.FieldEntityID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				_m.EntityID = new(uuid.UUID)
				*_m.EntityID = *value.S.(*uuid.UUID)
			}
		case aicapturesessionitem.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = aicapturesessionitem.Status(value.String)
			}
		case aicapturesessionitem.FieldUploadedPhotoIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_photo_ids", values[i])
			} else if value.Valid {
				_m.UploadedPhotoIds = value.String
			}
		case aicapturesessionitem.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AICaptureSessionItem.
// This includes values selected through modifiers, order, etc.
func (_m *AICaptureSessionItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the AICaptureSessionItem entity.
func (_m *AICaptureSessionItem) QuerySession() *AICaptureSessionQuery {
	return NewAICaptureSessionItemClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this AICaptureSessionItem.
// Note that you need to call AICaptureSessionItem.Unwrap() before calling this method if this AICaptureSessionItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AICaptureSessionItem) Update() *AICaptureSessionItemUpdateOne {
	return NewAICaptureSessionItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AICaptureSessionItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AICaptureSessionItem) Unwrap() *AICaptureSessionItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AICaptureSessionItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AICaptureSessionItem) String() string {
	var builder strings.Builder
	builder.WriteString("AICaptureSessionItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionID))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	if v := _m.EntityID; v != nil {
		builder.WriteString("entity_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("uploaded_photo_ids=")
	builder.WriteString(_m.UploadedPhotoIds)
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(_m.ErrorCode)
	builder.WriteByte(')')
	return builder.String()
}

// AICaptureSessionItems is a parsable slice of AICaptureSessionItem.
type AICaptureSessionItems []*AICaptureSessionItem
