// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturephoto"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesessionitem"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// AICaptureSessionQuery is the builder for querying AICaptureSession entities.
type AICaptureSessionQuery struct {
	config
	ctx          *QueryContext
	order        []aicapturesession.OrderOption
	inters       []Interceptor
	predicates   []predicate.AICaptureSession
	withGroup    *GroupQuery
	withUser     *UserQuery
	withLocation *EntityQuery
	withPhotos   *AICapturePhotoQuery
	withItems    *AICaptureSessionItemQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AICaptureSessionQuery builder.
func (_q *AICaptureSessionQuery) Where(ps ...predicate.AICaptureSession) *AICaptureSessionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AICaptureSessionQuery) Limit(limit int) *AICaptureSessionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AICaptureSessionQuery) Offset(offset int) *AICaptureSessionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AICaptureSessionQuery) Unique(unique bool) *AICaptureSessionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AICaptureSessionQuery) Order(o ...aicapturesession.OrderOption) *AICaptureSessionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGroup chains the current query on the "group" edge.
func (_q *AICaptureSessionQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(aicapturesession.Table, aicapturesession.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, aicapturesession.GroupTable, aicapturesession.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *AICaptureSessionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(aicapturesession.Table, aicapturesession.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, aicapturesession.UserTable, aicapturesession.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLocation chains the current query on the "location" edge.
func (_q *AICaptureSessionQuery) QueryLocation() *EntityQuery {
	query := (&EntityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(aicapturesession.Table, aicapturesession.FieldID, selector),
			sqlgraph.To(entity.Table, entity.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, aicapturesession.LocationTable, aicapturesession.LocationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPhotos chains the current query on the "photos" edge.
func (_q *AICaptureSessionQuery) QueryPhotos() *AICapturePhotoQuery {
	query := (&AICapturePhotoClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(aicapturesession.Table, aicapturesession.FieldID, selector),
			sqlgraph.To(aicapturephoto.Table, aicapturephoto.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, aicapturesession.PhotosTable, aicapturesession.PhotosColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryItems chains the current query on the "items" edge.
func (_q *AICaptureSessionQuery) QueryItems() *AICaptureSessionItemQuery {
	query := (&AICaptureSessionItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(aicapturesession.Table, aicapturesession.FieldID, selector),
			sqlgraph.To(aicapturesessionitem.Table, aicapturesessionitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, aicapturesession.ItemsTable, aicapturesession.ItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AICaptureSession entity from the query.
// Returns a *NotFoundError when no AICaptureSession was found.
func (_q *AICaptureSessionQuery) First(ctx context.Context) (*AICaptureSession, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{aicapturesession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AICaptureSessionQuery) FirstX(ctx context.Context) *AICaptureSession {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AICaptureSession ID from the query.
// Returns a *NotFoundError when no AICaptureSession ID was found.
func (_q *AICaptureSessionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{aicapturesession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AICaptureSessionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AICaptureSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AICaptureSession entity is found.
// Returns a *NotFoundError when no AICaptureSession entities are found.
func (_q *AICaptureSessionQuery) Only(ctx context.Context) (*AICaptureSession, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{aicapturesession.Label}
	default:
		return nil, &NotSingularError{aicapturesession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AICaptureSessionQuery) OnlyX(ctx context.Context) *AICaptureSession {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AICaptureSession ID in the query.
// Returns a *NotSingularError when more than one AICaptureSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AICaptureSessionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{aicapturesession.Label}
	default:
		err = &NotSingularError{aicapturesession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AICaptureSessionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AICaptureSessions.
func (_q *AICaptureSessionQuery) All(ctx context.Context) ([]*AICaptureSession, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AICaptureSession, *AICaptureSessionQuery]()
	return withInterceptors[[]*AICaptureSession](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AICaptureSessionQuery) AllX(ctx context.Context) []*AICaptureSession {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AICaptureSession IDs.
func (_q *AICaptureSessionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(aicapturesession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AICaptureSessionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AICaptureSessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AICaptureSessionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AICaptureSessionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AICaptureSessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AICaptureSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AICaptureSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AICaptureSessionQuery) Clone() *AICaptureSessionQuery {
	if _q == nil {
		return nil
	}
	return &AICaptureSessionQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]aicapturesession.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.AICaptureSession{}, _q.predicates...),
		withGroup:    _q.withGroup.Clone(),
		withUser:     _q.withUser.Clone(),
		withLocation: _q.withLocation.Clone(),
		withPhotos:   _q.withPhotos.Clone(),
		withItems:    _q.withItems.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AICaptureSessionQuery) WithGroup(opts ...func(*GroupQuery)) *AICaptureSessionQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AICaptureSessionQuery) WithUser(opts ...func(*UserQuery)) *AICaptureSessionQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithLocation tells the query-builder to eager-load the nodes that are connected to
// the "location" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AICaptureSessionQuery) WithLocation(opts ...func(*EntityQuery)) *AICaptureSessionQuery {
	query := (&EntityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLocation = query
	return _q
}

// WithPhotos tells the query-builder to eager-load the nodes that are connected to
// the "photos" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AICaptureSessionQuery) WithPhotos(opts ...func(*AICapturePhotoQuery)) *AICaptureSessionQuery {
	query := (&AICapturePhotoClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPhotos = query
	return _q
}

// WithItems tells the query-builder to eager-load the nodes that are connected to
// the "items" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AICaptureSessionQuery) WithItems(opts ...func(*AICaptureSessionItemQuery)) *AICaptureSessionQuery {
	query := (&AICaptureSessionItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withItems = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AICaptureSession.Query().
//		GroupBy(aicapturesession.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AICaptureSessionQuery) GroupBy(field string, fields ...string) *AICaptureSessionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AICaptureSessionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = aicapturesession.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AICaptureSession.Query().
//		Select(aicapturesession.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *AICaptureSessionQuery) Select(fields ...string) *AICaptureSessionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AICaptureSessionSelect{AICaptureSessionQuery: _q}
	sbuild.label = aicapturesession.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AICaptureSessionSelect configured with the given aggregations.
func (_q *AICaptureSessionQuery) Aggregate(fns ...AggregateFunc) *AICaptureSessionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AICaptureSessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !aicapturesession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AICaptureSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AICaptureSession, error) {
	var (
		nodes       = []*AICaptureSession{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withGroup != nil,
			_q.withUser != nil,
			_q.withLocation != nil,
			_q.withPhotos != nil,
			_q.withItems != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AICaptureSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AICaptureSession{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *AICaptureSession, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *AICaptureSession, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLocation; query != nil {
		if err := _q.loadLocation(ctx, query, nodes, nil,
			func(n *AICaptureSession, e *Entity) { n.Edges.Location = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPhotos; query != nil {
		if err := _q.loadPhotos(ctx, query, nodes,
			func(n *AICaptureSession) { n.Edges.Photos = []*AICapturePhoto{} },
			func(n *AICaptureSession, e *AICapturePhoto) { n.Edges.Photos = append(n.Edges.Photos, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withItems; query != nil {
		if err := _q.loadItems(ctx, query, nodes,
			func(n *AICaptureSession) { n.Edges.Items = []*AICaptureSessionItem{} },
			func(n *AICaptureSession, e *AICaptureSessionItem) { n.Edges.Items = append(n.Edges.Items, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AICaptureSessionQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*AICaptureSession, init func(*AICaptureSession), assign func(*AICaptureSession, *Group)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AICaptureSession)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AICaptureSessionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*AICaptureSession, init func(*AICaptureSession), assign func(*AICaptureSession, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AICaptureSession)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AICaptureSessionQuery) loadLocation(ctx context.Context, query *EntityQuery, nodes []*AICaptureSession, init func(*AICaptureSession), assign func(*AICaptureSession, *Entity)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AICaptureSession)
	for i := range nodes {
		if nodes[i].LocationID == nil {
			continue
		}
		fk := *nodes[i].LocationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(entity.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "location_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AICaptureSessionQuery) loadPhotos(ctx context.Context, query *AICapturePhotoQuery, nodes []*AICaptureSession, init func(*AICaptureSession), assign func(*AICaptureSession, *AICapturePhoto)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*AICaptureSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(aicapturephoto.FieldSessionID)
	}
	query.Where(predicate.AICapturePhoto(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(aicapturesession.PhotosColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AICaptureSessionQuery) loadItems(ctx context.Context, query *AICaptureSessionItemQuery, nodes []*AICaptureSession, init func(*AICaptureSession), assign func(*AICaptureSession, *AICaptureSessionItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*AICaptureSession)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(aicapturesessionitem.FieldSessionID)
	}
	query.Where(predicate.AICaptureSessionItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(aicapturesession.ItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SessionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "session_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AICaptureSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AICaptureSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(aicapturesession.Table, aicapturesession.Columns, sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aicapturesession.FieldID)
		for i := range fields {
			if fields[i] != aicapturesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(aicapturesession.FieldGroupID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(aicapturesession.FieldUserID)
		}
		if _q.withLocation != nil {
			_spec.Node.AddColumnOnce(aicapturesession.FieldLocationID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AICaptureSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(aicapturesession.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = aicapturesession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AICaptureSessionGroupBy is the group-by builder for AICaptureSession entities.
type AICaptureSessionGroupBy struct {
	selector
	build *AICaptureSessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AICaptureSessionGroupBy) Aggregate(fns ...AggregateFunc) *AICaptureSessionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AICaptureSessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AICaptureSessionQuery, *AICaptureSessionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AICaptureSessionGroupBy) sqlScan(ctx context.Context, root *AICaptureSessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AICaptureSessionSelect is the builder for selecting fields of AICaptureSession entities.
type AICaptureSessionSelect struct {
	*AICaptureSessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AICaptureSessionSelect) Aggregate(fns ...AggregateFunc) *AICaptureSessionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AICaptureSessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AICaptureSessionQuery, *AICaptureSessionSelect](ctx, _s.AICaptureSessionQuery, _s, _s.inters, v)
}

func (_s *AICaptureSessionSelect) sqlScan(ctx context.Context, root *AICaptureSessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
