// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturephoto"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesessionitem"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// AICaptureSessionCreate is the builder for creating a AICaptureSession entity.
type AICaptureSessionCreate struct {
	config
	mutation *AICaptureSessionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AICaptureSessionCreate) SetCreatedAt(v time.Time) *AICaptureSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableCreatedAt(v *time.Time) *AICaptureSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AICaptureSessionCreate) SetUpdatedAt(v time.Time) *AICaptureSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableUpdatedAt(v *time.Time) *AICaptureSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *AICaptureSessionCreate) SetGroupID(v uuid.UUID) *AICaptureSessionCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AICaptureSessionCreate) SetUserID(v uuid.UUID) *AICaptureSessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetLocationID sets the "location_id" field.
func (_c *AICaptureSessionCreate) SetLocationID(v uuid.UUID) *AICaptureSessionCreate {
	_c.mutation.SetLocationID(v)
	return _c
}

// SetNillableLocationID sets the "location_id" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableLocationID(v *uuid.UUID) *AICaptureSessionCreate {
	if v != nil {
		_c.SetLocationID(*v)
	}
	return _c
}

// SetLocationNameSnapshot sets the "location_name_snapshot" field.
func (_c *AICaptureSessionCreate) SetLocationNameSnapshot(v string) *AICaptureSessionCreate {
	_c.mutation.SetLocationNameSnapshot(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AICaptureSessionCreate) SetStatus(v aicapturesession.Status) *AICaptureSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableStatus(v *aicapturesession.Status) *AICaptureSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDraftJSON sets the "draft_json" field.
func (_c *AICaptureSessionCreate) SetDraftJSON(v string) *AICaptureSessionCreate {
	_c.mutation.SetDraftJSON(v)
	return _c
}

// SetNillableDraftJSON sets the "draft_json" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableDraftJSON(v *string) *AICaptureSessionCreate {
	if v != nil {
		_c.SetDraftJSON(*v)
	}
	return _c
}

// SetDraftRevision sets the "draft_revision" field.
func (_c *AICaptureSessionCreate) SetDraftRevision(v int) *AICaptureSessionCreate {
	_c.mutation.SetDraftRevision(v)
	return _c
}

// SetNillableDraftRevision sets the "draft_revision" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableDraftRevision(v *int) *AICaptureSessionCreate {
	if v != nil {
		_c.SetDraftRevision(*v)
	}
	return _c
}

// SetAnalysisAttempts sets the "analysis_attempts" field.
func (_c *AICaptureSessionCreate) SetAnalysisAttempts(v int) *AICaptureSessionCreate {
	_c.mutation.SetAnalysisAttempts(v)
	return _c
}

// SetNillableAnalysisAttempts sets the "analysis_attempts" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableAnalysisAttempts(v *int) *AICaptureSessionCreate {
	if v != nil {
		_c.SetAnalysisAttempts(*v)
	}
	return _c
}

// SetPhotoCount sets the "photo_count" field.
func (_c *AICaptureSessionCreate) SetPhotoCount(v int) *AICaptureSessionCreate {
	_c.mutation.SetPhotoCount(v)
	return _c
}

// SetNillablePhotoCount sets the "photo_count" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillablePhotoCount(v *int) *AICaptureSessionCreate {
	if v != nil {
		_c.SetPhotoCount(*v)
	}
	return _c
}

// SetWorkerLeaseUntil sets the "worker_lease_until" field.
func (_c *AICaptureSessionCreate) SetWorkerLeaseUntil(v time.Time) *AICaptureSessionCreate {
	_c.mutation.SetWorkerLeaseUntil(v)
	return _c
}

// SetNillableWorkerLeaseUntil sets the "worker_lease_until" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableWorkerLeaseUntil(v *time.Time) *AICaptureSessionCreate {
	if v != nil {
		_c.SetWorkerLeaseUntil(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *AICaptureSessionCreate) SetErrorCode(v string) *AICaptureSessionCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableErrorCode(v *string) *AICaptureSessionCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *AICaptureSessionCreate) SetErrorMessage(v string) *AICaptureSessionCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableErrorMessage(v *string) *AICaptureSessionCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *AICaptureSessionCreate) SetFinishedAt(v time.Time) *AICaptureSessionCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableFinishedAt(v *time.Time) *AICaptureSessionCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetAnalyzedAt sets the "analyzed_at" field.
func (_c *AICaptureSessionCreate) SetAnalyzedAt(v time.Time) *AICaptureSessionCreate {
	_c.mutation.SetAnalyzedAt(v)
	return _c
}

// SetNillableAnalyzedAt sets the "analyzed_at" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableAnalyzedAt(v *time.Time) *AICaptureSessionCreate {
	if v != nil {
		_c.SetAnalyzedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *AICaptureSessionCreate) SetCompletedAt(v time.Time) *AICaptureSessionCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableCompletedAt(v *time.Time) *AICaptureSessionCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AICaptureSessionCreate) SetExpiresAt(v time.Time) *AICaptureSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableExpiresAt(v *time.Time) *AICaptureSessionCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AICaptureSessionCreate) SetID(v uuid.UUID) *AICaptureSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AICaptureSessionCreate) SetNillableID(v *uuid.UUID) *AICaptureSessionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *AICaptureSessionCreate) SetGroup(v *Group) *AICaptureSessionCreate {
	return _c.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *AICaptureSessionCreate) SetUser(v *User) *AICaptureSessionCreate {
	return _c.SetUserID(v.ID)
}

// SetLocation sets the "location" edge to the Entity entity.
func (_c *AICaptureSessionCreate) SetLocation(v *Entity) *AICaptureSessionCreate {
	return _c.SetLocationID(v.ID)
}

// AddPhotoIDs adds the "photos" edge to the AICapturePhoto entity by IDs.
func (_c *AICaptureSessionCreate) AddPhotoIDs(ids ...uuid.UUID) *AICaptureSessionCreate {
	_c.mutation.AddPhotoIDs(ids...)
	return _c
}

// AddPhotos adds the "photos" edges to the AICapturePhoto entity.
func (_c *AICaptureSessionCreate) AddPhotos(v ...*AICapturePhoto) *AICaptureSessionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPhotoIDs(ids...)
}

// AddItemIDs adds the "items" edge to the AICaptureSessionItem entity by IDs.
func (_c *AICaptureSessionCreate) AddItemIDs(ids ...uuid.UUID) *AICaptureSessionCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the AICaptureSessionItem entity.
func (_c *AICaptureSessionCreate) AddItems(v ...*AICaptureSessionItem) *AICaptureSessionCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the AICaptureSessionMutation object of the builder.
func (_c *AICaptureSessionCreate) Mutation() *AICaptureSessionMutation {
	return _c.mutation
}

// Save creates the AICaptureSession in the database.
func (_c *AICaptureSessionCreate) Save(ctx context.Context) (*AICaptureSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AICaptureSessionCreate) SaveX(ctx context.Context) *AICaptureSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AICaptureSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AICaptureSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AICaptureSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := aicapturesession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := aicapturesession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := aicapturesession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DraftRevision(); !ok {
		v := aicapturesession.DefaultDraftRevision
		_c.mutation.SetDraftRevision(v)
	}
	if _, ok := _c.mutation.AnalysisAttempts(); !ok {
		v := aicapturesession.DefaultAnalysisAttempts
		_c.mutation.SetAnalysisAttempts(v)
	}
	if _, ok := _c.mutation.PhotoCount(); !ok {
		v := aicapturesession.DefaultPhotoCount
		_c.mutation.SetPhotoCount(v)
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		v := aicapturesession.DefaultExpiresAt()
		_c.mutation.SetExpiresAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := aicapturesession.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AICaptureSessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AICaptureSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AICaptureSession.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "AICaptureSession.group_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AICaptureSession.user_id"`)}
	}
	if _, ok := _c.mutation.LocationNameSnapshot(); !ok {
		return &ValidationError{Name: "location_name_snapshot", err: errors.New(`ent: missing required field "AICaptureSession.location_name_snapshot"`)}
	}
	if v, ok := _c.mutation.LocationNameSnapshot(); ok {
		if err := aicapturesession.LocationNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "location_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.location_name_snapshot": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AICaptureSession.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := aicapturesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DraftRevision(); !ok {
		return &ValidationError{Name: "draft_revision", err: errors.New(`ent: missing required field "AICaptureSession.draft_revision"`)}
	}
	if _, ok := _c.mutation.AnalysisAttempts(); !ok {
		return &ValidationError{Name: "analysis_attempts", err: errors.New(`ent: missing required field "AICaptureSession.analysis_attempts"`)}
	}
	if _, ok := _c.mutation.PhotoCount(); !ok {
		return &ValidationError{Name: "photo_count", err: errors.New(`ent: missing required field "AICaptureSession.photo_count"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := aicapturesession.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.error_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorMessage(); ok {
		if err := aicapturesession.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "AICaptureSession.error_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AICaptureSession.expires_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "AICaptureSession.group"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AICaptureSession.user"`)}
	}
	return nil
}

func (_c *AICaptureSessionCreate) sqlSave(ctx context.Context) (*AICaptureSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AICaptureSessionCreate) createSpec() (*AICaptureSession, *sqlgraph.CreateSpec) {
	var (
		_node = &AICaptureSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aicapturesession.Table, sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(aicapturesession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(aicapturesession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LocationNameSnapshot(); ok {
		_spec.SetField(aicapturesession.FieldLocationNameSnapshot, field.TypeString, value)
		_node.LocationNameSnapshot = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(aicapturesession.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DraftJSON(); ok {
		_spec.SetField(aicapturesession.FieldDraftJSON, field.TypeString, value)
		_node.DraftJSON = value
	}
	if value, ok := _c.mutation.DraftRevision(); ok {
		_spec.SetField(aicapturesession.FieldDraftRevision, field.TypeInt, value)
		_node.DraftRevision = value
	}
	if value, ok := _c.mutation.AnalysisAttempts(); ok {
		_spec.SetField(aicapturesession.FieldAnalysisAttempts, field.TypeInt, value)
		_node.AnalysisAttempts = value
	}
	if value, ok := _c.mutation.PhotoCount(); ok {
		_spec.SetField(aicapturesession.FieldPhotoCount, field.TypeInt, value)
		_node.PhotoCount = value
	}
	if value, ok := _c.mutation.WorkerLeaseUntil(); ok {
		_spec.SetField(aicapturesession.FieldWorkerLeaseUntil, field.TypeTime, value)
		_node.WorkerLeaseUntil = &value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(aicapturesession.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(aicapturesession.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(aicapturesession.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.AnalyzedAt(); ok {
		_spec.SetField(aicapturesession.FieldAnalyzedAt, field.TypeTime, value)
		_node.AnalyzedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(aicapturesession.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(aicapturesession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.GroupTable,
			Columns: []string{aicapturesession.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.UserTable,
			Columns: []string{aicapturesession.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesession.LocationTable,
			Columns: []string{aicapturesession.LocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LocationID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PhotosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.PhotosTable,
			Columns: []string{aicapturesession.PhotosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aicapturesession.ItemsTable,
			Columns: []string{aicapturesession.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesessionitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AICaptureSessionCreateBulk is the builder for creating many AICaptureSession entities in bulk.
type AICaptureSessionCreateBulk struct {
	config
	err      error
	builders []*AICaptureSessionCreate
}

// Save creates the AICaptureSession entities in the database.
func (_c *AICaptureSessionCreateBulk) Save(ctx context.Context) ([]*AICaptureSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AICaptureSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AICaptureSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AICaptureSessionCreateBulk) SaveX(ctx context.Context) []*AICaptureSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AICaptureSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AICaptureSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
