// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturephoto"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesession"
)

// AICapturePhoto is the model entity for the AICapturePhoto schema.
type AICapturePhoto struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// ClientPhotoID holds the value of the "client_photo_id" field.
	ClientPhotoID uuid.UUID `json:"client_photo_id,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// CaptureGroupID holds the value of the "capture_group_id" field.
	CaptureGroupID *uuid.UUID `json:"capture_group_id,omitempty"`
	// OriginalName holds the value of the "original_name" field.
	OriginalName string `json:"original_name,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// ContentHash holds the value of the "content_hash" field.
	ContentHash string `json:"content_hash,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AICapturePhotoQuery when eager-loading is set.
	Edges        AICapturePhotoEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AICapturePhotoEdges holds the relations/edges for other nodes in the graph.
type AICapturePhotoEdges struct {
	// Session holds the value of the session edge.
	Session *AICaptureSession `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AICapturePhotoEdges) SessionOrErr() (*AICaptureSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aicapturesession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AICapturePhoto) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aicapturephoto.FieldCaptureGroupID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case aicapturephoto.FieldPosition, aicapturephoto.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case aicapturephoto.FieldOriginalName, aicapturephoto.FieldPath, aicapturephoto.FieldMimeType, aicapturephoto.FieldContentHash:
			values[i] = new(sql.NullString)
		case aicapturephoto.FieldCreatedAt, aicapturephoto.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case aicapturephoto.FieldID, aicapturephoto.FieldSessionID, aicapturephoto.FieldClientPhotoID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AICapturePhoto fields.
func (_m *AICapturePhoto) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aicapturephoto.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case aicapturephoto.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case aicapturephoto.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case aicapturephoto.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				_m.SessionID = *value
			}
		case aicapturephoto.FieldClientPhotoID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field client_photo_id", values[i])
			} else if value != nil {
				_m.ClientPhotoID = *value
			}
		case aicapturephoto.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case aicapturephoto.FieldCaptureGroupID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field capture_group_id", values[i])
			} else if value.Valid {
				_m.CaptureGroupID = new(uuid.UUID)
				*_m.CaptureGroupID = *value.S.(*uuid.UUID)
			}
		case aicapturephoto.FieldOriginalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_name", values[i])
			} else if value.Valid {
				_m.OriginalName = value.String
			}
		case aicapturephoto.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case aicapturephoto.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case aicapturephoto.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case aicapturephoto.FieldContentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_hash", values[i])
			} else if value.Valid {
				_m.ContentHash = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AICapturePhoto.
// This includes values selected through modifiers, order, etc.
func (_m *AICapturePhoto) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the AICapturePhoto entity.
func (_m *AICapturePhoto) QuerySession() *AICaptureSessionQuery {
	return NewAICapturePhotoClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this AICapturePhoto.
// Note that you need to call AICapturePhoto.Unwrap() before calling this method if this AICapturePhoto
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AICapturePhoto) Update() *AICapturePhotoUpdateOne {
	return NewAICapturePhotoClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AICapturePhoto entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AICapturePhoto) Unwrap() *AICapturePhoto {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AICapturePhoto is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AICapturePhoto) String() string {
	var builder strings.Builder
	builder.WriteString("AICapturePhoto(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionID))
	builder.WriteString(", ")
	builder.WriteString("client_photo_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientPhotoID))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	if v := _m.CaptureGroupID; v != nil {
		builder.WriteString("capture_group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("original_name=")
	builder.WriteString(_m.OriginalName)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("content_hash=")
	builder.WriteString(_m.ContentHash)
	builder.WriteByte(')')
	return builder.String()
}

// AICapturePhotos is a parsable slice of AICapturePhoto.
type AICapturePhotos []*AICapturePhoto
