// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturephoto"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// AICapturePhotoUpdate is the builder for updating AICapturePhoto entities.
type AICapturePhotoUpdate struct {
	config
	hooks    []Hook
	mutation *AICapturePhotoMutation
}

// Where appends a list predicates to the AICapturePhotoUpdate builder.
func (_u *AICapturePhotoUpdate) Where(ps ...predicate.AICapturePhoto) *AICapturePhotoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AICapturePhotoUpdate) SetUpdatedAt(v time.Time) *AICapturePhotoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AICapturePhotoUpdate) SetSessionID(v uuid.UUID) *AICapturePhotoUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AICapturePhotoUpdate) SetNillableSessionID(v *uuid.UUID) *AICapturePhotoUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetClientPhotoID sets the "client_photo_id" field.
func (_u *AICapturePhotoUpdate) SetClientPhotoID(v uuid.UUID) *AICapturePhotoUpdate {
	_u.mutation.SetClientPhotoID(v)
	return _u
}

// SetNillableClientPhotoID sets the "client_photo_id" field if the given value is not nil.
func (_u *AICapturePhotoUpdate) SetNillableClientPhotoID(v *uuid.UUID) *AICapturePhotoUpdate {
	if v != nil {
		_u.SetClientPhotoID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *AICapturePhotoUpdate) SetPosition(v int) *AICapturePhotoUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *AICapturePhotoUpdate) SetNillablePosition(v *int) *AICapturePhotoUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *AICapturePhotoUpdate) AddPosition(v int) *AICapturePhotoUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetCaptureGroupID sets the "capture_group_id" field.
func (_u *AICapturePhotoUpdate) SetCaptureGroupID(v uuid.UUID) *AICapturePhotoUpdate {
	_u.mutation.SetCaptureGroupID(v)
	return _u
}

// SetNillableCaptureGroupID sets the "capture_group_id" field if the given value is not nil.
func (_u *AICapturePhotoUpdate) SetNillableCaptureGroupID(v *uuid.UUID) *AICapturePhotoUpdate {
	if v != nil {
		_u.SetCaptureGroupID(*v)
	}
	return _u
}

// ClearCaptureGroupID clears the value of the "capture_group_id" field.
func (_u *AICapturePhotoUpdate) ClearCaptureGroupID() *AICapturePhotoUpdate {
	_u.mutation.ClearCaptureGroupID()
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *AICapturePhotoUpdate) SetOriginalName(v string) *AICapturePhotoUpdate {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *AICapturePhotoUpdate) SetNillableOriginalName(v *string) *AICapturePhotoUpdate {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *AICapturePhotoUpdate) SetPath(v string) *AICapturePhotoUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AICapturePhotoUpdate) SetNillablePath(v *string) *AICapturePhotoUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *AICapturePhotoUpdate) SetMimeType(v string) *AICapturePhotoUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *AICapturePhotoUpdate) SetNillableMimeType(v *string) *AICapturePhotoUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *AICapturePhotoUpdate) SetSizeBytes(v int64) *AICapturePhotoUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *AICapturePhotoUpdate) SetNillableSizeBytes(v *int64) *AICapturePhotoUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *AICapturePhotoUpdate) AddSizeBytes(v int64) *AICapturePhotoUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *AICapturePhotoUpdate) SetContentHash(v string) *AICapturePhotoUpdate {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *AICapturePhotoUpdate) SetNillableContentHash(v *string) *AICapturePhotoUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the AICaptureSession entity.
func (_u *AICapturePhotoUpdate) SetSession(v *AICaptureSession) *AICapturePhotoUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the AICapturePhotoMutation object of the builder.
func (_u *AICapturePhotoUpdate) Mutation() *AICapturePhotoMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the AICaptureSession entity.
func (_u *AICapturePhotoUpdate) ClearSession() *AICapturePhotoUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AICapturePhotoUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AICapturePhotoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AICapturePhotoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AICapturePhotoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AICapturePhotoUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aicapturephoto.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AICapturePhotoUpdate) check() error {
	if v, ok := _u.mutation.Position(); ok {
		if err := aicapturephoto.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.position": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalName(); ok {
		if err := aicapturephoto.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := aicapturephoto.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := aicapturephoto.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.size_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := aicapturephoto.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.content_hash": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AICapturePhoto.session"`)
	}
	return nil
}

func (_u *AICapturePhotoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aicapturephoto.Table, aicapturephoto.Columns, sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aicapturephoto.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClientPhotoID(); ok {
		_spec.SetField(aicapturephoto.FieldClientPhotoID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(aicapturephoto.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(aicapturephoto.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CaptureGroupID(); ok {
		_spec.SetField(aicapturephoto.FieldCaptureGroupID, field.TypeUUID, value)
	}
	if _u.mutation.CaptureGroupIDCleared() {
		_spec.ClearField(aicapturephoto.FieldCaptureGroupID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(aicapturephoto.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(aicapturephoto.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(aicapturephoto.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(aicapturephoto.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(aicapturephoto.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(aicapturephoto.FieldContentHash, field.TypeString, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturephoto.SessionTable,
			Columns: []string{aicapturephoto.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturephoto.SessionTable,
			Columns: []string{aicapturephoto.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aicapturephoto.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AICapturePhotoUpdateOne is the builder for updating a single AICapturePhoto entity.
type AICapturePhotoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AICapturePhotoMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AICapturePhotoUpdateOne) SetUpdatedAt(v time.Time) *AICapturePhotoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AICapturePhotoUpdateOne) SetSessionID(v uuid.UUID) *AICapturePhotoUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AICapturePhotoUpdateOne) SetNillableSessionID(v *uuid.UUID) *AICapturePhotoUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetClientPhotoID sets the "client_photo_id" field.
func (_u *AICapturePhotoUpdateOne) SetClientPhotoID(v uuid.UUID) *AICapturePhotoUpdateOne {
	_u.mutation.SetClientPhotoID(v)
	return _u
}

// SetNillableClientPhotoID sets the "client_photo_id" field if the given value is not nil.
func (_u *AICapturePhotoUpdateOne) SetNillableClientPhotoID(v *uuid.UUID) *AICapturePhotoUpdateOne {
	if v != nil {
		_u.SetClientPhotoID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *AICapturePhotoUpdateOne) SetPosition(v int) *AICapturePhotoUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *AICapturePhotoUpdateOne) SetNillablePosition(v *int) *AICapturePhotoUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *AICapturePhotoUpdateOne) AddPosition(v int) *AICapturePhotoUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetCaptureGroupID sets the "capture_group_id" field.
func (_u *AICapturePhotoUpdateOne) SetCaptureGroupID(v uuid.UUID) *AICapturePhotoUpdateOne {
	_u.mutation.SetCaptureGroupID(v)
	return _u
}

// SetNillableCaptureGroupID sets the "capture_group_id" field if the given value is not nil.
func (_u *AICapturePhotoUpdateOne) SetNillableCaptureGroupID(v *uuid.UUID) *AICapturePhotoUpdateOne {
	if v != nil {
		_u.SetCaptureGroupID(*v)
	}
	return _u
}

// ClearCaptureGroupID clears the value of the "capture_group_id" field.
func (_u *AICapturePhotoUpdateOne) ClearCaptureGroupID() *AICapturePhotoUpdateOne {
	_u.mutation.ClearCaptureGroupID()
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *AICapturePhotoUpdateOne) SetOriginalName(v string) *AICapturePhotoUpdateOne {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *AICapturePhotoUpdateOne) SetNillableOriginalName(v *string) *AICapturePhotoUpdateOne {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *AICapturePhotoUpdateOne) SetPath(v string) *AICapturePhotoUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AICapturePhotoUpdateOne) SetNillablePath(v *string) *AICapturePhotoUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *AICapturePhotoUpdateOne) SetMimeType(v string) *AICapturePhotoUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *AICapturePhotoUpdateOne) SetNillableMimeType(v *string) *AICapturePhotoUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *AICapturePhotoUpdateOne) SetSizeBytes(v int64) *AICapturePhotoUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *AICapturePhotoUpdateOne) SetNillableSizeBytes(v *int64) *AICapturePhotoUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *AICapturePhotoUpdateOne) AddSizeBytes(v int64) *AICapturePhotoUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *AICapturePhotoUpdateOne) SetContentHash(v string) *AICapturePhotoUpdateOne {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *AICapturePhotoUpdateOne) SetNillableContentHash(v *string) *AICapturePhotoUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the AICaptureSession entity.
func (_u *AICapturePhotoUpdateOne) SetSession(v *AICaptureSession) *AICapturePhotoUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the AICapturePhotoMutation object of the builder.
func (_u *AICapturePhotoUpdateOne) Mutation() *AICapturePhotoMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the AICaptureSession entity.
func (_u *AICapturePhotoUpdateOne) ClearSession() *AICapturePhotoUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the AICapturePhotoUpdate builder.
func (_u *AICapturePhotoUpdateOne) Where(ps ...predicate.AICapturePhoto) *AICapturePhotoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AICapturePhotoUpdateOne) Select(field string, fields ...string) *AICapturePhotoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AICapturePhoto entity.
func (_u *AICapturePhotoUpdateOne) Save(ctx context.Context) (*AICapturePhoto, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AICapturePhotoUpdateOne) SaveX(ctx context.Context) *AICapturePhoto {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AICapturePhotoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AICapturePhotoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AICapturePhotoUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := aicapturephoto.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AICapturePhotoUpdateOne) check() error {
	if v, ok := _u.mutation.Position(); ok {
		if err := aicapturephoto.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.position": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalName(); ok {
		if err := aicapturephoto.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := aicapturephoto.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := aicapturephoto.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.size_bytes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := aicapturephoto.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "AICapturePhoto.content_hash": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AICapturePhoto.session"`)
	}
	return nil
}

func (_u *AICapturePhotoUpdateOne) sqlSave(ctx context.Context) (_node *AICapturePhoto, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aicapturephoto.Table, aicapturephoto.Columns, sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AICapturePhoto.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aicapturephoto.FieldID)
		for _, f := range fields {
			if !aicapturephoto.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aicapturephoto.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(aicapturephoto.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClientPhotoID(); ok {
		_spec.SetField(aicapturephoto.FieldClientPhotoID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(aicapturephoto.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(aicapturephoto.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CaptureGroupID(); ok {
		_spec.SetField(aicapturephoto.FieldCaptureGroupID, field.TypeUUID, value)
	}
	if _u.mutation.CaptureGroupIDCleared() {
		_spec.ClearField(aicapturephoto.FieldCaptureGroupID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(aicapturephoto.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(aicapturephoto.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(aicapturephoto.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(aicapturephoto.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(aicapturephoto.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(aicapturephoto.FieldContentHash, field.TypeString, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturephoto.SessionTable,
			Columns: []string{aicapturephoto.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturephoto.SessionTable,
			Columns: []string{aicapturephoto.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AICapturePhoto{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aicapturephoto.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
