// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/user"
)

// AICaptureSession is the model entity for the AICaptureSession schema.
type AICaptureSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID uuid.UUID `json:"group_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// LocationID holds the value of the "location_id" field.
	LocationID *uuid.UUID `json:"location_id,omitempty"`
	// LocationNameSnapshot holds the value of the "location_name_snapshot" field.
	LocationNameSnapshot string `json:"location_name_snapshot,omitempty"`
	// Status holds the value of the "status" field.
	Status aicapturesession.Status `json:"status,omitempty"`
	// DraftJSON holds the value of the "draft_json" field.
	DraftJSON string `json:"draft_json,omitempty"`
	// DraftRevision holds the value of the "draft_revision" field.
	DraftRevision int `json:"draft_revision,omitempty"`
	// CaptureRevision holds the value of the "capture_revision" field.
	CaptureRevision int `json:"capture_revision,omitempty"`
	// AnalysisAttempts holds the value of the "analysis_attempts" field.
	AnalysisAttempts int `json:"analysis_attempts,omitempty"`
	// PhotoCount holds the value of the "photo_count" field.
	PhotoCount int `json:"photo_count,omitempty"`
	// WorkerLeaseUntil holds the value of the "worker_lease_until" field.
	WorkerLeaseUntil *time.Time `json:"worker_lease_until,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// AnalyzedAt holds the value of the "analyzed_at" field.
	AnalyzedAt *time.Time `json:"analyzed_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AICaptureSessionQuery when eager-loading is set.
	Edges        AICaptureSessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AICaptureSessionEdges holds the relations/edges for other nodes in the graph.
type AICaptureSessionEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Location holds the value of the location edge.
	Location *Entity `json:"location,omitempty"`
	// Photos holds the value of the photos edge.
	Photos []*AICapturePhoto `json:"photos,omitempty"`
	// Items holds the value of the items edge.
	Items []*AICaptureSessionItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AICaptureSessionEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AICaptureSessionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// LocationOrErr returns the Location value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AICaptureSessionEdges) LocationOrErr() (*Entity, error) {
	if e.Location != nil {
		return e.Location, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: entity.Label}
	}
	return nil, &NotLoadedError{edge: "location"}
}

// PhotosOrErr returns the Photos value or an error if the edge
// was not loaded in eager-loading.
func (e AICaptureSessionEdges) PhotosOrErr() ([]*AICapturePhoto, error) {
	if e.loadedTypes[3] {
		return e.Photos, nil
	}
	return nil, &NotLoadedError{edge: "photos"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e AICaptureSessionEdges) ItemsOrErr() ([]*AICaptureSessionItem, error) {
	if e.loadedTypes[4] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AICaptureSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aicapturesession.FieldLocationID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case aicapturesession.FieldDraftRevision, aicapturesession.FieldCaptureRevision, aicapturesession.FieldAnalysisAttempts, aicapturesession.FieldPhotoCount:
			values[i] = new(sql.NullInt64)
		case aicapturesession.FieldLocationNameSnapshot, aicapturesession.FieldStatus, aicapturesession.FieldDraftJSON, aicapturesession.FieldErrorCode, aicapturesession.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case aicapturesession.FieldCreatedAt, aicapturesession.FieldUpdatedAt, aicapturesession.FieldWorkerLeaseUntil, aicapturesession.FieldFinishedAt, aicapturesession.FieldAnalyzedAt, aicapturesession.FieldCompletedAt, aicapturesession.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case aicapturesession.FieldID, aicapturesession.FieldGroupID, aicapturesession.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AICaptureSession fields.
func (_m *AICaptureSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aicapturesession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case aicapturesession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case aicapturesession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case aicapturesession.FieldGroupID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value != nil {
				_m.GroupID = *value
			}
		case aicapturesession.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case aicapturesession.FieldLocationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field location_id", values[i])
			} else if value.Valid {
				_m.LocationID = new(uuid.UUID)
				*_m.LocationID = *value.S.(*uuid.UUID)
			}
		case aicapturesession.FieldLocationNameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location_name_snapshot", values[i])
			} else if value.Valid {
				_m.LocationNameSnapshot = value.String
			}
		case aicapturesession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = aicapturesession.Status(value.String)
			}
		case aicapturesession.FieldDraftJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field draft_json", values[i])
			} else if value.Valid {
				_m.DraftJSON = value.String
			}
		case aicapturesession.FieldDraftRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field draft_revision", values[i])
			} else if value.Valid {
				_m.DraftRevision = int(value.Int64)
			}
		case aicapturesession.FieldCaptureRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field capture_revision", values[i])
			} else if value.Valid {
				_m.CaptureRevision = int(value.Int64)
			}
		case aicapturesession.FieldAnalysisAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field analysis_attempts", values[i])
			} else if value.Valid {
				_m.AnalysisAttempts = int(value.Int64)
			}
		case aicapturesession.FieldPhotoCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field photo_count", values[i])
			} else if value.Valid {
				_m.PhotoCount = int(value.Int64)
			}
		case aicapturesession.FieldWorkerLeaseUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field worker_lease_until", values[i])
			} else if value.Valid {
				_m.WorkerLeaseUntil = new(time.Time)
				*_m.WorkerLeaseUntil = value.Time
			}
		case aicapturesession.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = value.String
			}
		case aicapturesession.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case aicapturesession.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case aicapturesession.FieldAnalyzedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field analyzed_at", values[i])
			} else if value.Valid {
				_m.AnalyzedAt = new(time.Time)
				*_m.AnalyzedAt = value.Time
			}
		case aicapturesession.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case aicapturesession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AICaptureSession.
// This includes values selected through modifiers, order, etc.
func (_m *AICaptureSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the AICaptureSession entity.
func (_m *AICaptureSession) QueryGroup() *GroupQuery {
	return NewAICaptureSessionClient(_m.config).QueryGroup(_m)
}

// QueryUser queries the "user" edge of the AICaptureSession entity.
func (_m *AICaptureSession) QueryUser() *UserQuery {
	return NewAICaptureSessionClient(_m.config).QueryUser(_m)
}

// QueryLocation queries the "location" edge of the AICaptureSession entity.
func (_m *AICaptureSession) QueryLocation() *EntityQuery {
	return NewAICaptureSessionClient(_m.config).QueryLocation(_m)
}

// QueryPhotos queries the "photos" edge of the AICaptureSession entity.
func (_m *AICaptureSession) QueryPhotos() *AICapturePhotoQuery {
	return NewAICaptureSessionClient(_m.config).QueryPhotos(_m)
}

// QueryItems queries the "items" edge of the AICaptureSession entity.
func (_m *AICaptureSession) QueryItems() *AICaptureSessionItemQuery {
	return NewAICaptureSessionClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this AICaptureSession.
// Note that you need to call AICaptureSession.Unwrap() before calling this method if this AICaptureSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AICaptureSession) Update() *AICaptureSessionUpdateOne {
	return NewAICaptureSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AICaptureSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AICaptureSession) Unwrap() *AICaptureSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AICaptureSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AICaptureSession) String() string {
	var builder strings.Builder
	builder.WriteString("AICaptureSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.LocationID; v != nil {
		builder.WriteString("location_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("location_name_snapshot=")
	builder.WriteString(_m.LocationNameSnapshot)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("draft_json=")
	builder.WriteString(_m.DraftJSON)
	builder.WriteString(", ")
	builder.WriteString("draft_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.DraftRevision))
	builder.WriteString(", ")
	builder.WriteString("capture_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.CaptureRevision))
	builder.WriteString(", ")
	builder.WriteString("analysis_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnalysisAttempts))
	builder.WriteString(", ")
	builder.WriteString("photo_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PhotoCount))
	builder.WriteString(", ")
	if v := _m.WorkerLeaseUntil; v != nil {
		builder.WriteString("worker_lease_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(_m.ErrorCode)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AnalyzedAt; v != nil {
		builder.WriteString("analyzed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AICaptureSessions is a parsable slice of AICaptureSession.
type AICaptureSessions []*AICaptureSession
