// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesession"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturesessionitem"
)

// AICaptureSessionItemCreate is the builder for creating a AICaptureSessionItem entity.
type AICaptureSessionItemCreate struct {
	config
	mutation *AICaptureSessionItemMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AICaptureSessionItemCreate) SetCreatedAt(v time.Time) *AICaptureSessionItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AICaptureSessionItemCreate) SetNillableCreatedAt(v *time.Time) *AICaptureSessionItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AICaptureSessionItemCreate) SetUpdatedAt(v time.Time) *AICaptureSessionItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AICaptureSessionItemCreate) SetNillableUpdatedAt(v *time.Time) *AICaptureSessionItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AICaptureSessionItemCreate) SetSessionID(v uuid.UUID) *AICaptureSessionItemCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *AICaptureSessionItemCreate) SetClientID(v string) *AICaptureSessionItemCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *AICaptureSessionItemCreate) SetEntityID(v uuid.UUID) *AICaptureSessionItemCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_c *AICaptureSessionItemCreate) SetNillableEntityID(v *uuid.UUID) *AICaptureSessionItemCreate {
	if v != nil {
		_c.SetEntityID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AICaptureSessionItemCreate) SetStatus(v aicapturesessionitem.Status) *AICaptureSessionItemCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AICaptureSessionItemCreate) SetNillableStatus(v *aicapturesessionitem.Status) *AICaptureSessionItemCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUploadedPhotoIds sets the "uploaded_photo_ids" field.
func (_c *AICaptureSessionItemCreate) SetUploadedPhotoIds(v string) *AICaptureSessionItemCreate {
	_c.mutation.SetUploadedPhotoIds(v)
	return _c
}

// SetNillableUploadedPhotoIds sets the "uploaded_photo_ids" field if the given value is not nil.
func (_c *AICaptureSessionItemCreate) SetNillableUploadedPhotoIds(v *string) *AICaptureSessionItemCreate {
	if v != nil {
		_c.SetUploadedPhotoIds(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *AICaptureSessionItemCreate) SetErrorCode(v string) *AICaptureSessionItemCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *AICaptureSessionItemCreate) SetNillableErrorCode(v *string) *AICaptureSessionItemCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AICaptureSessionItemCreate) SetID(v uuid.UUID) *AICaptureSessionItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AICaptureSessionItemCreate) SetNillableID(v *uuid.UUID) *AICaptureSessionItemCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSession sets the "session" edge to the AICaptureSession entity.
func (_c *AICaptureSessionItemCreate) SetSession(v *AICaptureSession) *AICaptureSessionItemCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the AICaptureSessionItemMutation object of the builder.
func (_c *AICaptureSessionItemCreate) Mutation() *AICaptureSessionItemMutation {
	return _c.mutation
}

// Save creates the AICaptureSessionItem in the database.
func (_c *AICaptureSessionItemCreate) Save(ctx context.Context) (*AICaptureSessionItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AICaptureSessionItemCreate) SaveX(ctx context.Context) *AICaptureSessionItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AICaptureSessionItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AICaptureSessionItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AICaptureSessionItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := aicapturesessionitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := aicapturesessionitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := aicapturesessionitem.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.UploadedPhotoIds(); !ok {
		v := aicapturesessionitem.DefaultUploadedPhotoIds
		_c.mutation.SetUploadedPhotoIds(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := aicapturesessionitem.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AICaptureSessionItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AICaptureSessionItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AICaptureSessionItem.updated_at"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "AICaptureSessionItem.session_id"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "AICaptureSessionItem.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := aicapturesessionitem.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "AICaptureSessionItem.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AICaptureSessionItem.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := aicapturesessionitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AICaptureSessionItem.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UploadedPhotoIds(); !ok {
		return &ValidationError{Name: "uploaded_photo_ids", err: errors.New(`ent: missing required field "AICaptureSessionItem.uploaded_photo_ids"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := aicapturesessionitem.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "AICaptureSessionItem.error_code": %w`, err)}
		}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "AICaptureSessionItem.session"`)}
	}
	return nil
}

func (_c *AICaptureSessionItemCreate) sqlSave(ctx context.Context) (*AICaptureSessionItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AICaptureSessionItemCreate) createSpec() (*AICaptureSessionItem, *sqlgraph.CreateSpec) {
	var (
		_node = &AICaptureSessionItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aicapturesessionitem.Table, sqlgraph.NewFieldSpec(aicapturesessionitem.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(aicapturesessionitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(aicapturesessionitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(aicapturesessionitem.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.EntityID(); ok {
		_spec.SetField(aicapturesessionitem.FieldEntityID, field.TypeUUID, value)
		_node.EntityID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(aicapturesessionitem.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UploadedPhotoIds(); ok {
		_spec.SetField(aicapturesessionitem.FieldUploadedPhotoIds, field.TypeString, value)
		_node.UploadedPhotoIds = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(aicapturesessionitem.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   aicapturesessionitem.SessionTable,
			Columns: []string{aicapturesessionitem.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aicapturesession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AICaptureSessionItemCreateBulk is the builder for creating many AICaptureSessionItem entities in bulk.
type AICaptureSessionItemCreateBulk struct {
	config
	err      error
	builders []*AICaptureSessionItemCreate
}

// Save creates the AICaptureSessionItem entities in the database.
func (_c *AICaptureSessionItemCreateBulk) Save(ctx context.Context) ([]*AICaptureSessionItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AICaptureSessionItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AICaptureSessionItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AICaptureSessionItemCreateBulk) SaveX(ctx context.Context) []*AICaptureSessionItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AICaptureSessionItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AICaptureSessionItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
