// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/aicapturephoto"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// AICapturePhotoDelete is the builder for deleting a AICapturePhoto entity.
type AICapturePhotoDelete struct {
	config
	hooks    []Hook
	mutation *AICapturePhotoMutation
}

// Where appends a list predicates to the AICapturePhotoDelete builder.
func (_d *AICapturePhotoDelete) Where(ps ...predicate.AICapturePhoto) *AICapturePhotoDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AICapturePhotoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AICapturePhotoDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AICapturePhotoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(aicapturephoto.Table, sqlgraph.NewFieldSpec(aicapturephoto.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AICapturePhotoDeleteOne is the builder for deleting a single AICapturePhoto entity.
type AICapturePhotoDeleteOne struct {
	_d *AICapturePhotoDelete
}

// Where appends a list predicates to the AICapturePhotoDelete builder.
func (_d *AICapturePhotoDeleteOne) Where(ps ...predicate.AICapturePhoto) *AICapturePhotoDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AICapturePhotoDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{aicapturephoto.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AICapturePhotoDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
