// Code generated by ent, DO NOT EDIT.

package aicapturesession

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the aicapturesession type in the database.
	Label = "ai_capture_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldLocationID holds the string denoting the location_id field in the database.
	FieldLocationID = "location_id"
	// FieldLocationNameSnapshot holds the string denoting the location_name_snapshot field in the database.
	FieldLocationNameSnapshot = "location_name_snapshot"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDraftJSON holds the string denoting the draft_json field in the database.
	FieldDraftJSON = "draft_json"
	// FieldDraftRevision holds the string denoting the draft_revision field in the database.
	FieldDraftRevision = "draft_revision"
	// FieldCaptureRevision holds the string denoting the capture_revision field in the database.
	FieldCaptureRevision = "capture_revision"
	// FieldAnalysisAttempts holds the string denoting the analysis_attempts field in the database.
	FieldAnalysisAttempts = "analysis_attempts"
	// FieldAnalysisNextAttemptAt holds the string denoting the analysis_next_attempt_at field in the database.
	FieldAnalysisNextAttemptAt = "analysis_next_attempt_at"
	// FieldPhotoCount holds the string denoting the photo_count field in the database.
	FieldPhotoCount = "photo_count"
	// FieldWorkerLeaseUntil holds the string denoting the worker_lease_until field in the database.
	FieldWorkerLeaseUntil = "worker_lease_until"
	// FieldReanalysisJSON holds the string denoting the reanalysis_json field in the database.
	FieldReanalysisJSON = "reanalysis_json"
	// FieldReanalysisStatus holds the string denoting the reanalysis_status field in the database.
	FieldReanalysisStatus = "reanalysis_status"
	// FieldReanalysisNextAttemptAt holds the string denoting the reanalysis_next_attempt_at field in the database.
	FieldReanalysisNextAttemptAt = "reanalysis_next_attempt_at"
	// FieldReanalysisWorkerLeaseUntil holds the string denoting the reanalysis_worker_lease_until field in the database.
	FieldReanalysisWorkerLeaseUntil = "reanalysis_worker_lease_until"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldAnalyzedAt holds the string denoting the analyzed_at field in the database.
	FieldAnalyzedAt = "analyzed_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeLocation holds the string denoting the location edge name in mutations.
	EdgeLocation = "location"
	// EdgePhotos holds the string denoting the photos edge name in mutations.
	EdgePhotos = "photos"
	// EdgeItems holds the string denoting the items edge name in mutations.
	EdgeItems = "items"
	// Table holds the table name of the aicapturesession in the database.
	Table = "ai_capture_sessions"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "ai_capture_sessions"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "ai_capture_sessions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// LocationTable is the table that holds the location relation/edge.
	LocationTable = "ai_capture_sessions"
	// LocationInverseTable is the table name for the Entity entity.
	// It exists in this package in order to avoid circular dependency with the "entity" package.
	LocationInverseTable = "entities"
	// LocationColumn is the table column denoting the location relation/edge.
	LocationColumn = "location_id"
	// PhotosTable is the table that holds the photos relation/edge.
	PhotosTable = "ai_capture_photos"
	// PhotosInverseTable is the table name for the AICapturePhoto entity.
	// It exists in this package in order to avoid circular dependency with the "aicapturephoto" package.
	PhotosInverseTable = "ai_capture_photos"
	// PhotosColumn is the table column denoting the photos relation/edge.
	PhotosColumn = "session_id"
	// ItemsTable is the table that holds the items relation/edge.
	ItemsTable = "ai_capture_session_items"
	// ItemsInverseTable is the table name for the AICaptureSessionItem entity.
	// It exists in this package in order to avoid circular dependency with the "aicapturesessionitem" package.
	ItemsInverseTable = "ai_capture_session_items"
	// ItemsColumn is the table column denoting the items relation/edge.
	ItemsColumn = "session_id"
)

// Columns holds all SQL columns for aicapturesession fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGroupID,
	FieldUserID,
	FieldLocationID,
	FieldLocationNameSnapshot,
	FieldStatus,
	FieldDraftJSON,
	FieldDraftRevision,
	FieldCaptureRevision,
	FieldAnalysisAttempts,
	FieldAnalysisNextAttemptAt,
	FieldPhotoCount,
	FieldWorkerLeaseUntil,
	FieldReanalysisJSON,
	FieldReanalysisStatus,
	FieldReanalysisNextAttemptAt,
	FieldReanalysisWorkerLeaseUntil,
	FieldErrorCode,
	FieldErrorMessage,
	FieldFinishedAt,
	FieldAnalyzedAt,
	FieldCompletedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// LocationNameSnapshotValidator is a validator for the "location_name_snapshot" field. It is called by the builders before save.
	LocationNameSnapshotValidator func(string) error
	// DefaultDraftRevision holds the default value on creation for the "draft_revision" field.
	DefaultDraftRevision int
	// DefaultCaptureRevision holds the default value on creation for the "capture_revision" field.
	DefaultCaptureRevision int
	// DefaultAnalysisAttempts holds the default value on creation for the "analysis_attempts" field.
	DefaultAnalysisAttempts int
	// DefaultPhotoCount holds the default value on creation for the "photo_count" field.
	DefaultPhotoCount int
	// ReanalysisStatusValidator is a validator for the "reanalysis_status" field. It is called by the builders before save.
	ReanalysisStatusValidator func(string) error
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// ErrorMessageValidator is a validator for the "error_message" field. It is called by the builders before save.
	ErrorMessageValidator func(string) error
	// DefaultExpiresAt holds the default value on creation for the "expires_at" field.
	DefaultExpiresAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusCapturing is the default value of the Status enum.
const DefaultStatus = StatusCapturing

// Status values.
const (
	StatusCapturing      Status = "capturing"
	StatusQueued         Status = "queued"
	StatusAnalyzing      Status = "analyzing"
	StatusAnalysisFailed Status = "analysis_failed"
	StatusReadyForReview Status = "ready_for_review"
	StatusSubmitting     Status = "submitting"
	StatusCompleted      Status = "completed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusCapturing, StatusQueued, StatusAnalyzing, StatusAnalysisFailed, StatusReadyForReview, StatusSubmitting, StatusCompleted:
		return nil
	default:
		return fmt.Errorf("aicapturesession: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AICaptureSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByLocationID orders the results by the location_id field.
func ByLocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocationID, opts...).ToFunc()
}

// ByLocationNameSnapshot orders the results by the location_name_snapshot field.
func ByLocationNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocationNameSnapshot, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDraftJSON orders the results by the draft_json field.
func ByDraftJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDraftJSON, opts...).ToFunc()
}

// ByDraftRevision orders the results by the draft_revision field.
func ByDraftRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDraftRevision, opts...).ToFunc()
}

// ByCaptureRevision orders the results by the capture_revision field.
func ByCaptureRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaptureRevision, opts...).ToFunc()
}

// ByAnalysisAttempts orders the results by the analysis_attempts field.
func ByAnalysisAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnalysisAttempts, opts...).ToFunc()
}

// ByAnalysisNextAttemptAt orders the results by the analysis_next_attempt_at field.
func ByAnalysisNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnalysisNextAttemptAt, opts...).ToFunc()
}

// ByPhotoCount orders the results by the photo_count field.
func ByPhotoCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhotoCount, opts...).ToFunc()
}

// ByWorkerLeaseUntil orders the results by the worker_lease_until field.
func ByWorkerLeaseUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkerLeaseUntil, opts...).ToFunc()
}

// ByReanalysisJSON orders the results by the reanalysis_json field.
func ByReanalysisJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReanalysisJSON, opts...).ToFunc()
}

// ByReanalysisStatus orders the results by the reanalysis_status field.
func ByReanalysisStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReanalysisStatus, opts...).ToFunc()
}

// ByReanalysisNextAttemptAt orders the results by the reanalysis_next_attempt_at field.
func ByReanalysisNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReanalysisNextAttemptAt, opts...).ToFunc()
}

// ByReanalysisWorkerLeaseUntil orders the results by the reanalysis_worker_lease_until field.
func ByReanalysisWorkerLeaseUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReanalysisWorkerLeaseUntil, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByAnalyzedAt orders the results by the analyzed_at field.
func ByAnalyzedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnalyzedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByLocationField orders the results by location field.
func ByLocationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLocationStep(), sql.OrderByField(field, opts...))
	}
}

// ByPhotosCount orders the results by photos count.
func ByPhotosCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPhotosStep(), opts...)
	}
}

// ByPhotos orders the results by photos terms.
func ByPhotos(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPhotosStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByItemsCount orders the results by items count.
func ByItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newItemsStep(), opts...)
	}
}

// ByItems orders the results by items terms.
func ByItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newLocationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LocationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
	)
}
func newPhotosStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PhotosInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PhotosTable, PhotosColumn),
	)
}
func newItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
	)
}
