// Code generated by ent, DO NOT EDIT.

package aicapturesession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldGroupID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldUserID, v))
}

// LocationID applies equality check predicate on the "location_id" field. It's identical to LocationIDEQ.
func LocationID(v uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldLocationID, v))
}

// LocationNameSnapshot applies equality check predicate on the "location_name_snapshot" field. It's identical to LocationNameSnapshotEQ.
func LocationNameSnapshot(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldLocationNameSnapshot, v))
}

// DraftJSON applies equality check predicate on the "draft_json" field. It's identical to DraftJSONEQ.
func DraftJSON(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldDraftJSON, v))
}

// DraftRevision applies equality check predicate on the "draft_revision" field. It's identical to DraftRevisionEQ.
func DraftRevision(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldDraftRevision, v))
}

// AnalysisAttempts applies equality check predicate on the "analysis_attempts" field. It's identical to AnalysisAttemptsEQ.
func AnalysisAttempts(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldAnalysisAttempts, v))
}

// PhotoCount applies equality check predicate on the "photo_count" field. It's identical to PhotoCountEQ.
func PhotoCount(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldPhotoCount, v))
}

// WorkerLeaseUntil applies equality check predicate on the "worker_lease_until" field. It's identical to WorkerLeaseUntilEQ.
func WorkerLeaseUntil(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldWorkerLeaseUntil, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldErrorMessage, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldFinishedAt, v))
}

// AnalyzedAt applies equality check predicate on the "analyzed_at" field. It's identical to AnalyzedAtEQ.
func AnalyzedAt(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldAnalyzedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldCompletedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldGroupID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldUserID, vs...))
}

// LocationIDEQ applies the EQ predicate on the "location_id" field.
func LocationIDEQ(v uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldLocationID, v))
}

// LocationIDNEQ applies the NEQ predicate on the "location_id" field.
func LocationIDNEQ(v uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldLocationID, v))
}

// LocationIDIn applies the In predicate on the "location_id" field.
func LocationIDIn(vs ...uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldLocationID, vs...))
}

// LocationIDNotIn applies the NotIn predicate on the "location_id" field.
func LocationIDNotIn(vs ...uuid.UUID) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldLocationID, vs...))
}

// LocationIDIsNil applies the IsNil predicate on the "location_id" field.
func LocationIDIsNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIsNull(FieldLocationID))
}

// LocationIDNotNil applies the NotNil predicate on the "location_id" field.
func LocationIDNotNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotNull(FieldLocationID))
}

// LocationNameSnapshotEQ applies the EQ predicate on the "location_name_snapshot" field.
func LocationNameSnapshotEQ(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldLocationNameSnapshot, v))
}

// LocationNameSnapshotNEQ applies the NEQ predicate on the "location_name_snapshot" field.
func LocationNameSnapshotNEQ(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldLocationNameSnapshot, v))
}

// LocationNameSnapshotIn applies the In predicate on the "location_name_snapshot" field.
func LocationNameSnapshotIn(vs ...string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldLocationNameSnapshot, vs...))
}

// LocationNameSnapshotNotIn applies the NotIn predicate on the "location_name_snapshot" field.
func LocationNameSnapshotNotIn(vs ...string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldLocationNameSnapshot, vs...))
}

// LocationNameSnapshotGT applies the GT predicate on the "location_name_snapshot" field.
func LocationNameSnapshotGT(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldLocationNameSnapshot, v))
}

// LocationNameSnapshotGTE applies the GTE predicate on the "location_name_snapshot" field.
func LocationNameSnapshotGTE(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldLocationNameSnapshot, v))
}

// LocationNameSnapshotLT applies the LT predicate on the "location_name_snapshot" field.
func LocationNameSnapshotLT(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldLocationNameSnapshot, v))
}

// LocationNameSnapshotLTE applies the LTE predicate on the "location_name_snapshot" field.
func LocationNameSnapshotLTE(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldLocationNameSnapshot, v))
}

// LocationNameSnapshotContains applies the Contains predicate on the "location_name_snapshot" field.
func LocationNameSnapshotContains(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldContains(FieldLocationNameSnapshot, v))
}

// LocationNameSnapshotHasPrefix applies the HasPrefix predicate on the "location_name_snapshot" field.
func LocationNameSnapshotHasPrefix(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldHasPrefix(FieldLocationNameSnapshot, v))
}

// LocationNameSnapshotHasSuffix applies the HasSuffix predicate on the "location_name_snapshot" field.
func LocationNameSnapshotHasSuffix(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldHasSuffix(FieldLocationNameSnapshot, v))
}

// LocationNameSnapshotEqualFold applies the EqualFold predicate on the "location_name_snapshot" field.
func LocationNameSnapshotEqualFold(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEqualFold(FieldLocationNameSnapshot, v))
}

// LocationNameSnapshotContainsFold applies the ContainsFold predicate on the "location_name_snapshot" field.
func LocationNameSnapshotContainsFold(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldContainsFold(FieldLocationNameSnapshot, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldStatus, vs...))
}

// DraftJSONEQ applies the EQ predicate on the "draft_json" field.
func DraftJSONEQ(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldDraftJSON, v))
}

// DraftJSONNEQ applies the NEQ predicate on the "draft_json" field.
func DraftJSONNEQ(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldDraftJSON, v))
}

// DraftJSONIn applies the In predicate on the "draft_json" field.
func DraftJSONIn(vs ...string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldDraftJSON, vs...))
}

// DraftJSONNotIn applies the NotIn predicate on the "draft_json" field.
func DraftJSONNotIn(vs ...string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldDraftJSON, vs...))
}

// DraftJSONGT applies the GT predicate on the "draft_json" field.
func DraftJSONGT(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldDraftJSON, v))
}

// DraftJSONGTE applies the GTE predicate on the "draft_json" field.
func DraftJSONGTE(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldDraftJSON, v))
}

// DraftJSONLT applies the LT predicate on the "draft_json" field.
func DraftJSONLT(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldDraftJSON, v))
}

// DraftJSONLTE applies the LTE predicate on the "draft_json" field.
func DraftJSONLTE(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldDraftJSON, v))
}

// DraftJSONContains applies the Contains predicate on the "draft_json" field.
func DraftJSONContains(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldContains(FieldDraftJSON, v))
}

// DraftJSONHasPrefix applies the HasPrefix predicate on the "draft_json" field.
func DraftJSONHasPrefix(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldHasPrefix(FieldDraftJSON, v))
}

// DraftJSONHasSuffix applies the HasSuffix predicate on the "draft_json" field.
func DraftJSONHasSuffix(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldHasSuffix(FieldDraftJSON, v))
}

// DraftJSONIsNil applies the IsNil predicate on the "draft_json" field.
func DraftJSONIsNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIsNull(FieldDraftJSON))
}

// DraftJSONNotNil applies the NotNil predicate on the "draft_json" field.
func DraftJSONNotNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotNull(FieldDraftJSON))
}

// DraftJSONEqualFold applies the EqualFold predicate on the "draft_json" field.
func DraftJSONEqualFold(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEqualFold(FieldDraftJSON, v))
}

// DraftJSONContainsFold applies the ContainsFold predicate on the "draft_json" field.
func DraftJSONContainsFold(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldContainsFold(FieldDraftJSON, v))
}

// DraftRevisionEQ applies the EQ predicate on the "draft_revision" field.
func DraftRevisionEQ(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldDraftRevision, v))
}

// DraftRevisionNEQ applies the NEQ predicate on the "draft_revision" field.
func DraftRevisionNEQ(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldDraftRevision, v))
}

// DraftRevisionIn applies the In predicate on the "draft_revision" field.
func DraftRevisionIn(vs ...int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldDraftRevision, vs...))
}

// DraftRevisionNotIn applies the NotIn predicate on the "draft_revision" field.
func DraftRevisionNotIn(vs ...int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldDraftRevision, vs...))
}

// DraftRevisionGT applies the GT predicate on the "draft_revision" field.
func DraftRevisionGT(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldDraftRevision, v))
}

// DraftRevisionGTE applies the GTE predicate on the "draft_revision" field.
func DraftRevisionGTE(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldDraftRevision, v))
}

// DraftRevisionLT applies the LT predicate on the "draft_revision" field.
func DraftRevisionLT(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldDraftRevision, v))
}

// DraftRevisionLTE applies the LTE predicate on the "draft_revision" field.
func DraftRevisionLTE(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldDraftRevision, v))
}

// AnalysisAttemptsEQ applies the EQ predicate on the "analysis_attempts" field.
func AnalysisAttemptsEQ(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldAnalysisAttempts, v))
}

// AnalysisAttemptsNEQ applies the NEQ predicate on the "analysis_attempts" field.
func AnalysisAttemptsNEQ(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldAnalysisAttempts, v))
}

// AnalysisAttemptsIn applies the In predicate on the "analysis_attempts" field.
func AnalysisAttemptsIn(vs ...int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldAnalysisAttempts, vs...))
}

// AnalysisAttemptsNotIn applies the NotIn predicate on the "analysis_attempts" field.
func AnalysisAttemptsNotIn(vs ...int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldAnalysisAttempts, vs...))
}

// AnalysisAttemptsGT applies the GT predicate on the "analysis_attempts" field.
func AnalysisAttemptsGT(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldAnalysisAttempts, v))
}

// AnalysisAttemptsGTE applies the GTE predicate on the "analysis_attempts" field.
func AnalysisAttemptsGTE(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldAnalysisAttempts, v))
}

// AnalysisAttemptsLT applies the LT predicate on the "analysis_attempts" field.
func AnalysisAttemptsLT(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldAnalysisAttempts, v))
}

// AnalysisAttemptsLTE applies the LTE predicate on the "analysis_attempts" field.
func AnalysisAttemptsLTE(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldAnalysisAttempts, v))
}

// PhotoCountEQ applies the EQ predicate on the "photo_count" field.
func PhotoCountEQ(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldPhotoCount, v))
}

// PhotoCountNEQ applies the NEQ predicate on the "photo_count" field.
func PhotoCountNEQ(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldPhotoCount, v))
}

// PhotoCountIn applies the In predicate on the "photo_count" field.
func PhotoCountIn(vs ...int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldPhotoCount, vs...))
}

// PhotoCountNotIn applies the NotIn predicate on the "photo_count" field.
func PhotoCountNotIn(vs ...int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldPhotoCount, vs...))
}

// PhotoCountGT applies the GT predicate on the "photo_count" field.
func PhotoCountGT(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldPhotoCount, v))
}

// PhotoCountGTE applies the GTE predicate on the "photo_count" field.
func PhotoCountGTE(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldPhotoCount, v))
}

// PhotoCountLT applies the LT predicate on the "photo_count" field.
func PhotoCountLT(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldPhotoCount, v))
}

// PhotoCountLTE applies the LTE predicate on the "photo_count" field.
func PhotoCountLTE(v int) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldPhotoCount, v))
}

// WorkerLeaseUntilEQ applies the EQ predicate on the "worker_lease_until" field.
func WorkerLeaseUntilEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldWorkerLeaseUntil, v))
}

// WorkerLeaseUntilNEQ applies the NEQ predicate on the "worker_lease_until" field.
func WorkerLeaseUntilNEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldWorkerLeaseUntil, v))
}

// WorkerLeaseUntilIn applies the In predicate on the "worker_lease_until" field.
func WorkerLeaseUntilIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldWorkerLeaseUntil, vs...))
}

// WorkerLeaseUntilNotIn applies the NotIn predicate on the "worker_lease_until" field.
func WorkerLeaseUntilNotIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldWorkerLeaseUntil, vs...))
}

// WorkerLeaseUntilGT applies the GT predicate on the "worker_lease_until" field.
func WorkerLeaseUntilGT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldWorkerLeaseUntil, v))
}

// WorkerLeaseUntilGTE applies the GTE predicate on the "worker_lease_until" field.
func WorkerLeaseUntilGTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldWorkerLeaseUntil, v))
}

// WorkerLeaseUntilLT applies the LT predicate on the "worker_lease_until" field.
func WorkerLeaseUntilLT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldWorkerLeaseUntil, v))
}

// WorkerLeaseUntilLTE applies the LTE predicate on the "worker_lease_until" field.
func WorkerLeaseUntilLTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldWorkerLeaseUntil, v))
}

// WorkerLeaseUntilIsNil applies the IsNil predicate on the "worker_lease_until" field.
func WorkerLeaseUntilIsNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIsNull(FieldWorkerLeaseUntil))
}

// WorkerLeaseUntilNotNil applies the NotNil predicate on the "worker_lease_until" field.
func WorkerLeaseUntilNotNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotNull(FieldWorkerLeaseUntil))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldContainsFold(FieldErrorMessage, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotNull(FieldFinishedAt))
}

// AnalyzedAtEQ applies the EQ predicate on the "analyzed_at" field.
func AnalyzedAtEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldAnalyzedAt, v))
}

// AnalyzedAtNEQ applies the NEQ predicate on the "analyzed_at" field.
func AnalyzedAtNEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldAnalyzedAt, v))
}

// AnalyzedAtIn applies the In predicate on the "analyzed_at" field.
func AnalyzedAtIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldAnalyzedAt, vs...))
}

// AnalyzedAtNotIn applies the NotIn predicate on the "analyzed_at" field.
func AnalyzedAtNotIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldAnalyzedAt, vs...))
}

// AnalyzedAtGT applies the GT predicate on the "analyzed_at" field.
func AnalyzedAtGT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldAnalyzedAt, v))
}

// AnalyzedAtGTE applies the GTE predicate on the "analyzed_at" field.
func AnalyzedAtGTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldAnalyzedAt, v))
}

// AnalyzedAtLT applies the LT predicate on the "analyzed_at" field.
func AnalyzedAtLT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldAnalyzedAt, v))
}

// AnalyzedAtLTE applies the LTE predicate on the "analyzed_at" field.
func AnalyzedAtLTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldAnalyzedAt, v))
}

// AnalyzedAtIsNil applies the IsNil predicate on the "analyzed_at" field.
func AnalyzedAtIsNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIsNull(FieldAnalyzedAt))
}

// AnalyzedAtNotNil applies the NotNil predicate on the "analyzed_at" field.
func AnalyzedAtNotNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotNull(FieldAnalyzedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotNull(FieldCompletedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.FieldLTE(FieldExpiresAt, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.AICaptureSession {
	return predicate.AICaptureSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.AICaptureSession {
	return predicate.AICaptureSession(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AICaptureSession {
	return predicate.AICaptureSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AICaptureSession {
	return predicate.AICaptureSession(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLocation applies the HasEdge predicate on the "location" edge.
func HasLocation() predicate.AICaptureSession {
	return predicate.AICaptureSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LocationTable, LocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocationWith applies the HasEdge predicate on the "location" edge with a given conditions (other predicates).
func HasLocationWith(preds ...predicate.Entity) predicate.AICaptureSession {
	return predicate.AICaptureSession(func(s *sql.Selector) {
		step := newLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPhotos applies the HasEdge predicate on the "photos" edge.
func HasPhotos() predicate.AICaptureSession {
	return predicate.AICaptureSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PhotosTable, PhotosColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPhotosWith applies the HasEdge predicate on the "photos" edge with a given conditions (other predicates).
func HasPhotosWith(preds ...predicate.AICapturePhoto) predicate.AICaptureSession {
	return predicate.AICaptureSession(func(s *sql.Selector) {
		step := newPhotosStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.AICaptureSession {
	return predicate.AICaptureSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.AICaptureSessionItem) predicate.AICaptureSession {
	return predicate.AICaptureSession(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AICaptureSession) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AICaptureSession) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AICaptureSession) predicate.AICaptureSession {
	return predicate.AICaptureSession(sql.NotPredicates(p))
}
