// Code generated by ent, DO NOT EDIT.

package aicapturephoto

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldUpdatedAt, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldSessionID, v))
}

// ClientPhotoID applies equality check predicate on the "client_photo_id" field. It's identical to ClientPhotoIDEQ.
func ClientPhotoID(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldClientPhotoID, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldPosition, v))
}

// CaptureGroupID applies equality check predicate on the "capture_group_id" field. It's identical to CaptureGroupIDEQ.
func CaptureGroupID(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldCaptureGroupID, v))
}

// OriginalName applies equality check predicate on the "original_name" field. It's identical to OriginalNameEQ.
func OriginalName(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldOriginalName, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldPath, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldMimeType, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldSizeBytes, v))
}

// ContentHash applies equality check predicate on the "content_hash" field. It's identical to ContentHashEQ.
func ContentHash(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldContentHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldUpdatedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldSessionID, vs...))
}

// ClientPhotoIDEQ applies the EQ predicate on the "client_photo_id" field.
func ClientPhotoIDEQ(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldClientPhotoID, v))
}

// ClientPhotoIDNEQ applies the NEQ predicate on the "client_photo_id" field.
func ClientPhotoIDNEQ(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldClientPhotoID, v))
}

// ClientPhotoIDIn applies the In predicate on the "client_photo_id" field.
func ClientPhotoIDIn(vs ...uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldClientPhotoID, vs...))
}

// ClientPhotoIDNotIn applies the NotIn predicate on the "client_photo_id" field.
func ClientPhotoIDNotIn(vs ...uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldClientPhotoID, vs...))
}

// ClientPhotoIDGT applies the GT predicate on the "client_photo_id" field.
func ClientPhotoIDGT(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldClientPhotoID, v))
}

// ClientPhotoIDGTE applies the GTE predicate on the "client_photo_id" field.
func ClientPhotoIDGTE(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldClientPhotoID, v))
}

// ClientPhotoIDLT applies the LT predicate on the "client_photo_id" field.
func ClientPhotoIDLT(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldClientPhotoID, v))
}

// ClientPhotoIDLTE applies the LTE predicate on the "client_photo_id" field.
func ClientPhotoIDLTE(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldClientPhotoID, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldPosition, v))
}

// CaptureGroupIDEQ applies the EQ predicate on the "capture_group_id" field.
func CaptureGroupIDEQ(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldCaptureGroupID, v))
}

// CaptureGroupIDNEQ applies the NEQ predicate on the "capture_group_id" field.
func CaptureGroupIDNEQ(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldCaptureGroupID, v))
}

// CaptureGroupIDIn applies the In predicate on the "capture_group_id" field.
func CaptureGroupIDIn(vs ...uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldCaptureGroupID, vs...))
}

// CaptureGroupIDNotIn applies the NotIn predicate on the "capture_group_id" field.
func CaptureGroupIDNotIn(vs ...uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldCaptureGroupID, vs...))
}

// CaptureGroupIDGT applies the GT predicate on the "capture_group_id" field.
func CaptureGroupIDGT(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldCaptureGroupID, v))
}

// CaptureGroupIDGTE applies the GTE predicate on the "capture_group_id" field.
func CaptureGroupIDGTE(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldCaptureGroupID, v))
}

// CaptureGroupIDLT applies the LT predicate on the "capture_group_id" field.
func CaptureGroupIDLT(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldCaptureGroupID, v))
}

// CaptureGroupIDLTE applies the LTE predicate on the "capture_group_id" field.
func CaptureGroupIDLTE(v uuid.UUID) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldCaptureGroupID, v))
}

// CaptureGroupIDIsNil applies the IsNil predicate on the "capture_group_id" field.
func CaptureGroupIDIsNil() predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIsNull(FieldCaptureGroupID))
}

// CaptureGroupIDNotNil applies the NotNil predicate on the "capture_group_id" field.
func CaptureGroupIDNotNil() predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotNull(FieldCaptureGroupID))
}

// OriginalNameEQ applies the EQ predicate on the "original_name" field.
func OriginalNameEQ(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldOriginalName, v))
}

// OriginalNameNEQ applies the NEQ predicate on the "original_name" field.
func OriginalNameNEQ(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldOriginalName, v))
}

// OriginalNameIn applies the In predicate on the "original_name" field.
func OriginalNameIn(vs ...string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldOriginalName, vs...))
}

// OriginalNameNotIn applies the NotIn predicate on the "original_name" field.
func OriginalNameNotIn(vs ...string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldOriginalName, vs...))
}

// OriginalNameGT applies the GT predicate on the "original_name" field.
func OriginalNameGT(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldOriginalName, v))
}

// OriginalNameGTE applies the GTE predicate on the "original_name" field.
func OriginalNameGTE(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldOriginalName, v))
}

// OriginalNameLT applies the LT predicate on the "original_name" field.
func OriginalNameLT(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldOriginalName, v))
}

// OriginalNameLTE applies the LTE predicate on the "original_name" field.
func OriginalNameLTE(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldOriginalName, v))
}

// OriginalNameContains applies the Contains predicate on the "original_name" field.
func OriginalNameContains(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldContains(FieldOriginalName, v))
}

// OriginalNameHasPrefix applies the HasPrefix predicate on the "original_name" field.
func OriginalNameHasPrefix(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldHasPrefix(FieldOriginalName, v))
}

// OriginalNameHasSuffix applies the HasSuffix predicate on the "original_name" field.
func OriginalNameHasSuffix(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldHasSuffix(FieldOriginalName, v))
}

// OriginalNameEqualFold applies the EqualFold predicate on the "original_name" field.
func OriginalNameEqualFold(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEqualFold(FieldOriginalName, v))
}

// OriginalNameContainsFold applies the ContainsFold predicate on the "original_name" field.
func OriginalNameContainsFold(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldContainsFold(FieldOriginalName, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldContainsFold(FieldPath, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldContainsFold(FieldMimeType, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldSizeBytes, v))
}

// ContentHashEQ applies the EQ predicate on the "content_hash" field.
func ContentHashEQ(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEQ(FieldContentHash, v))
}

// ContentHashNEQ applies the NEQ predicate on the "content_hash" field.
func ContentHashNEQ(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNEQ(FieldContentHash, v))
}

// ContentHashIn applies the In predicate on the "content_hash" field.
func ContentHashIn(vs ...string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldIn(FieldContentHash, vs...))
}

// ContentHashNotIn applies the NotIn predicate on the "content_hash" field.
func ContentHashNotIn(vs ...string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldNotIn(FieldContentHash, vs...))
}

// ContentHashGT applies the GT predicate on the "content_hash" field.
func ContentHashGT(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGT(FieldContentHash, v))
}

// ContentHashGTE applies the GTE predicate on the "content_hash" field.
func ContentHashGTE(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldGTE(FieldContentHash, v))
}

// ContentHashLT applies the LT predicate on the "content_hash" field.
func ContentHashLT(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLT(FieldContentHash, v))
}

// ContentHashLTE applies the LTE predicate on the "content_hash" field.
func ContentHashLTE(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldLTE(FieldContentHash, v))
}

// ContentHashContains applies the Contains predicate on the "content_hash" field.
func ContentHashContains(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldContains(FieldContentHash, v))
}

// ContentHashHasPrefix applies the HasPrefix predicate on the "content_hash" field.
func ContentHashHasPrefix(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldHasPrefix(FieldContentHash, v))
}

// ContentHashHasSuffix applies the HasSuffix predicate on the "content_hash" field.
func ContentHashHasSuffix(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldHasSuffix(FieldContentHash, v))
}

// ContentHashEqualFold applies the EqualFold predicate on the "content_hash" field.
func ContentHashEqualFold(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldEqualFold(FieldContentHash, v))
}

// ContentHashContainsFold applies the ContainsFold predicate on the "content_hash" field.
func ContentHashContainsFold(v string) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.FieldContainsFold(FieldContentHash, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.AICapturePhoto {
	return predicate.AICapturePhoto(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.AICaptureSession) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AICapturePhoto) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AICapturePhoto) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AICapturePhoto) predicate.AICapturePhoto {
	return predicate.AICapturePhoto(sql.NotPredicates(p))
}
